# Generated by Django 4.2.30 on 2026-06-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Indica si el usuario debe cambiar su contraseña en el próximo inicio de sesión', verbose_name='Debe cambiar contraseña'),
        ),
    ]
