# Generated by Django 4.2.30 on 2026-06-09 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('academic', '0001_initial'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividad',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlockComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('internal_weight', models.DecimalField(decimal_places=2, help_text='Peso del componente dentro del bloque de evaluación', max_digits=5, verbose_name='Ponderación Interna (%)')),
            ],
            options={
                'verbose_name': 'Componente de Bloque',
                'verbose_name_plural': 'Componentes de Bloque',
                'ordering': ['evaluation_block', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('internal_weight', models.DecimalField(decimal_places=2, help_text='Peso del indicador dentro de su componente', max_digits=5, verbose_name='Ponderación Interna (%)')),
                ('block_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='grading.blockcomponent', verbose_name='Componente de Bloque')),
            ],
            options={
                'verbose_name': 'Indicador de Componente',
                'verbose_name_plural': 'Indicadores de Componente',
                'ordering': ['block_component', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Evaluación',
                'verbose_name_plural': 'Tipos de Evaluación',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluativeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puntuación Máxima')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('is_interdisciplinary_project', models.BooleanField(default=False, help_text='Indica si esta actividad forma parte de un proyecto interdisciplinar', verbose_name='Es Proyecto Interdisciplinar')),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.activitytype', verbose_name='Tipo de Actividad')),
                ('component_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='grading.componentindicator', verbose_name='Indicador de Componente')),
                ('teacher_subject_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluative_activities', to='academic.teachersubjectsection', verbose_name='Docente-Materia-Sección')),
            ],
            options={
                'verbose_name': 'Actividad Evaluativa',
                'verbose_name_plural': 'Actividades Evaluativas',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='GradeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('applicable_sublevels', models.ManyToManyField(blank=True, related_name='grade_types', to='institutions.academicsublevel', verbose_name='Sublevels Aplicables')),
            ],
            options={
                'verbose_name': 'Tipo de Calificación',
                'verbose_name_plural': 'Tipos de Calificación',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PeriodGradeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('formative_avg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Promedio Formativo')),
                ('summative_avg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Promedio Sumativo')),
                ('final_avg_truncated', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Promedio Final Truncado')),
                ('requires_recovery', models.BooleanField(default=False, verbose_name='Requiere Recuperación')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Calculado en')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_summaries', to='academic.academicperiod', verbose_name='Período Académico')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_summaries', to='students.enrollment', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Resumen de Calificaciones del Período',
                'verbose_name_plural': 'Resúmenes de Calificaciones del Período',
            },
        ),
        migrations.CreateModel(
            name='PromotionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Estado de Promoción',
                'verbose_name_plural': 'Estados de Promoción',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QualitativeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('numeric_equivalence', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Equivalencia Numérica')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('applicable_sublevel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subnivel Aplicable')),
            ],
            options={
                'verbose_name': 'Escala Cualitativa',
                'verbose_name_plural': 'Escalas Cualitativas',
                'ordering': ['-numeric_equivalence'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Proceso de Recuperación',
                'verbose_name_plural': 'Tipos de Proceso de Recuperación',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único global para sincronización offline', unique=True, verbose_name='UUID')),
                ('numeric_score', models.DecimalField(blank=True, decimal_places=2, help_text='Calificación numérica obtenida (escala 1-10)', max_digits=5, null=True, verbose_name='Puntuación Numérica')),
                ('manually_overridden', models.BooleanField(default=False, verbose_name='Anulada Manualmente')),
                ('teacher_observation', models.TextField(blank=True, null=True, verbose_name='Observación del Docente')),
                ('sync_status', models.CharField(default='PENDIENTE', help_text='PENDIENTE, SINCRONIZADO o ERROR', max_length=20, verbose_name='Estado de Sincronización')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado en')),
                ('sync_version', models.PositiveIntegerField(default=1, help_text='Número de versión para control de conflictos offline', verbose_name='Versión de Sincronización')),
                ('device_origin', models.CharField(blank=True, max_length=40, null=True, verbose_name='Dispositivo de Origen')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.enrollment', verbose_name='Matrícula')),
                ('evaluative_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grading.evaluativeactivity', verbose_name='Actividad Evaluativa')),
                ('grade_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='grading.gradetype', verbose_name='Tipo de Calificación')),
                ('qualitative_scale', models.ForeignKey(blank=True, help_text='Escala cualitativa equivalente a la nota (si aplica)', null=True, on_delete=django.db.models.deletion.PROTECT, to='grading.qualitativescale', verbose_name='Escala Cualitativa')),
            ],
            options={
                'verbose_name': 'Nota de Actividad',
                'verbose_name_plural': 'Notas de Actividades',
            },
        ),
        migrations.CreateModel(
            name='RecoveryProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('initial_grade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota Inicial')),
                ('reinforcement_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota de Refuerzo')),
                ('improvement_eval_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota de Evaluación de Mejora')),
                ('final_calculated_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota Final Calculada')),
                ('family_notified', models.BooleanField(default=False, verbose_name='Familia Notificada')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('managed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_processes', to=settings.AUTH_USER_MODEL, verbose_name='Gestionado por')),
                ('period_grade_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_processes', to='grading.periodgradesummary', verbose_name='Resumen de Calificaciones')),
                ('process_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.recoveryprocesstype', verbose_name='Tipo de proceso')),
            ],
            options={
                'verbose_name': 'Proceso de Recuperación',
                'verbose_name_plural': 'Procesos de Recuperación',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('product_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota del producto')),
                ('presentation_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota de exposición')),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota final')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('sync_status', models.CharField(default='pending', max_length=20, verbose_name='Estado de Sincronización')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado el')),
                ('sync_version', models.PositiveIntegerField(default=0, verbose_name='Versión de Sincronización')),
                ('device_origin', models.CharField(blank=True, max_length=40, null=True, verbose_name='Dispositivo de Origen')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_notes', to='students.enrollment', verbose_name='Matrícula')),
                ('interdisciplinary_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_notes', to='academic.interdisciplinaryproject', verbose_name='Proyecto Interdisciplinario')),
            ],
            options={
                'verbose_name': 'Nota de Proyecto',
                'verbose_name_plural': 'Notas de Proyectos',
            },
        ),
        migrations.AddField(
            model_name='periodgradesummary',
            name='promotion_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.promotionstatus', verbose_name='Estado de Promoción'),
        ),
        migrations.AddField(
            model_name='periodgradesummary',
            name='qualitative_scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='grading.qualitativescale', verbose_name='Escala Cualitativa'),
        ),
        migrations.AddField(
            model_name='periodgradesummary',
            name='subject_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_summaries', to='academic.subjectoffering', verbose_name='Oferta de Asignatura'),
        ),
        migrations.CreateModel(
            name='GradeChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('previous_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota Anterior')),
                ('new_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota Nueva')),
                ('reason', models.TextField(verbose_name='Razón del Cambio')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='Modificado en')),
                ('modified_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('student_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='grading.studentnote', verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Historial de Cambio de Nota',
                'verbose_name_plural': 'Historial de Cambios de Notas',
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('weight_percentage', models.DecimalField(decimal_places=2, help_text='Porcentaje que representa este bloque en la nota final del período', max_digits=5, verbose_name='Porcentaje de Ponderación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_blocks', to='academic.academicperiod', verbose_name='Período Académico')),
                ('evaluation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.evaluationtype', verbose_name='Tipo de evaluación')),
            ],
            options={
                'verbose_name': 'Bloque de Evaluación',
                'verbose_name_plural': 'Bloques de Evaluación',
                'ordering': ['academic_period', 'evaluation_type'],
            },
        ),
        migrations.AddField(
            model_name='blockcomponent',
            name='evaluation_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='grading.evaluationblock', verbose_name='Bloque de Evaluación'),
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['enrollment', 'evaluative_activity'], name='grading_stu_enrollm_90708b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['sync_status'], name='grading_stu_sync_st_364ed8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectnote',
            unique_together={('enrollment', 'interdisciplinary_project')},
        ),
        migrations.AlterUniqueTogether(
            name='periodgradesummary',
            unique_together={('enrollment', 'subject_offering', 'academic_period')},
        ),
    ]
