# Generated by Django 6.0.4 on 2026-04-30 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('incident_date', models.DateField(help_text='Fecha en que ocurrió el incidente')),
                ('category', models.CharField(choices=[('disciplina', 'Disciplina'), ('academica', 'Académica'), ('social', 'Social'), ('asistencia', 'Asistencia')], help_text='Tipo de incidente', max_length=30)),
                ('severity', models.IntegerField(choices=[(1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], help_text='Nivel de gravedad del incidente')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del suceso', null=True)),
                ('family_notified', models.BooleanField(default=False, help_text='Indica si se ha comunicado a la familia')),
                ('sync_status', models.CharField(default='pending', max_length=20)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=0, help_text='Versión para control de sincronización')),
                ('device_origin', models.CharField(blank=True, help_text='Identificador del dispositivo de origen', max_length=40, null=True)),
                ('academic_period', models.ForeignKey(help_text='Período académico correspondiente', on_delete=django.db.models.deletion.CASCADE, to='academic.academic_period')),
                ('reported_by', models.ForeignKey(help_text='Usuario que realiza el reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Estudiante involucrado', on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(help_text='Fecha en la que se registra la asistencia')),
                ('status', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('T', 'Tardanza'), ('J', 'Justificado')], help_text='Estado de la asistencia', max_length=2)),
                ('observation', models.TextField(blank=True, help_text='Observaciones adicionales', null=True)),
                ('sync_status', models.CharField(default='pending', max_length=20)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=0, help_text='Versión para control de sincronización')),
                ('device_origin', models.CharField(blank=True, help_text='Identificador del dispositivo de origen', max_length=40, null=True)),
                ('academic_period', models.ForeignKey(help_text='Período académico correspondiente', on_delete=django.db.models.deletion.CASCADE, to='academic.academic_period')),
                ('student', models.ForeignKey(help_text='Estudiante evaluado', on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('teacher_subject_section', models.ForeignKey(help_text='Clase o sección a la que asiste', on_delete=django.db.models.deletion.CASCADE, to='academic.teacher_subject_section')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'academic_period'], name='grading_att_student_f7fabd_idx'), models.Index(fields=['teacher_subject_section', 'date'], name='grading_att_teacher_1e61d6_idx')],
                'unique_together': {('student', 'teacher_subject_section', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('note_value', models.DecimalField(decimal_places=2, help_text='Valor obtenido en la actividad', max_digits=5)),
                ('normalized_value', models.DecimalField(decimal_places=2, help_text='Valor de la nota normalizado (usualmente base 10)', max_digits=5)),
                ('observation', models.TextField(blank=True, help_text='Observaciones o comentarios del docente', null=True)),
                ('sync_status', models.CharField(default='pending', help_text='Estado de sincronización con el servidor', max_length=20)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, help_text='Indica si la nota está activa (no eliminada logicamente)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=0, help_text='Versión para control de cambios en sincronización')),
                ('device_origin', models.CharField(blank=True, help_text='ID o nombre del dispositivo de origen', max_length=40, null=True)),
                ('academic_activity', models.ForeignKey(help_text='Actividad académica evaluada', on_delete=django.db.models.deletion.CASCADE, to='academic.academic_activity')),
                ('academic_period', models.ForeignKey(help_text='Período académico correspondiente', on_delete=django.db.models.deletion.CASCADE, to='academic.academic_period')),
                ('student', models.ForeignKey(help_text='Estudiante evaluado', on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('teacher_subject_section', models.ForeignKey(help_text='Relación docente, materia y sección', on_delete=django.db.models.deletion.CASCADE, to='academic.teacher_subject_section')),
            ],
            options={
                'unique_together': {('student', 'academic_activity', 'academic_period', 'teacher_subject_section')},
            },
        ),
    ]
