# Generated by Django 4.2.30 on 2026-06-16 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividad',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlockComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('internal_weight', models.DecimalField(decimal_places=2, help_text='Peso del componente dentro del bloque de evaluación', max_digits=5, verbose_name='Ponderación Interna (%)')),
            ],
            options={
                'verbose_name': 'Componente de Bloque',
                'verbose_name_plural': 'Componentes de Bloque',
                'ordering': ['evaluation_block', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('block_type', models.CharField(blank=True, choices=[('FORMATIVA', 'Formativa'), ('SUMATIVA', 'Sumativa'), ('PROJECT', 'Proyecto')], max_length=20, null=True, verbose_name='Tipo de bloque')),
                ('weight_percentage', models.DecimalField(decimal_places=2, help_text='Porcentaje que representa este bloque en la nota final del período', max_digits=5, verbose_name='Porcentaje de Ponderación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Bloque de Evaluación',
                'verbose_name_plural': 'Bloques de Evaluación',
                'ordering': ['academic_period', 'subject_offering', 'block_type'],
            },
        ),
        migrations.CreateModel(
            name='EvaluativeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pendiente de sincronizar'), ('PROCESSING', 'En procesamiento'), ('SYNCED', 'Sincronizado'), ('ERROR', 'Error de sincronización'), ('CONFLICT', 'Conflicto detectado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de Sincronización')),
                ('sync_version', models.PositiveIntegerField(default=1, verbose_name='Versión de Sincronización')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado en')),
                ('device_origin', models.CharField(blank=True, max_length=40, null=True, verbose_name='Dispositivo de Origen')),
                ('conflict_resolved', models.BooleanField(default=False, verbose_name='Conflicto Resuelto')),
                ('conflict_notes', models.TextField(blank=True, default='', verbose_name='Notas de Conflicto')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puntuación Máxima')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('internal_weight', models.DecimalField(decimal_places=2, help_text='Peso de la actividad dentro de su componente', max_digits=5, verbose_name='Ponderación Interna (%)')),
            ],
            options={
                'verbose_name': 'Actividad Evaluativa',
                'verbose_name_plural': 'Actividades Evaluativas',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='GradeChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('previous_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota Anterior')),
                ('new_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota Nueva')),
                ('reason', models.TextField(verbose_name='Razón del Cambio')),
                ('reason_code', models.CharField(blank=True, max_length=30, verbose_name='Código de Razón')),
                ('origin', models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORT', 'Importación'), ('SYNC', 'Sincronización')], default='MANUAL', max_length=20, verbose_name='Origen')),
                ('device_origin', models.CharField(blank=True, max_length=40, null=True, verbose_name='Dispositivo de Origen')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='Modificado en')),
            ],
            options={
                'verbose_name': 'Historial de Cambio de Calificación',
                'verbose_name_plural': 'Historiales de Cambio de Calificación',
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='PeriodGradeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('formative_avg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Promedio Formativo')),
                ('summative_avg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Promedio Sumativo')),
                ('final_avg_truncated', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Promedio Final Truncado')),
                ('is_failing', models.BooleanField(default=False, verbose_name='Está Reprobando')),
                ('promotion_status', models.CharField(blank=True, choices=[('approved', 'Aprobado'), ('failed', 'Reprobado')], max_length=20, null=True, verbose_name='Estado de Promoción')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Calculado en')),
            ],
            options={
                'verbose_name': 'Resumen de Calificaciones del Período',
                'verbose_name_plural': 'Resúmenes de Calificaciones del Período',
            },
        ),
        migrations.CreateModel(
            name='QualitativeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('numeric_equivalence', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Equivalencia Numérica')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Escala Cualitativa',
                'verbose_name_plural': 'Escalas Cualitativas',
                'ordering': ['-numeric_equivalence'],
            },
        ),
        migrations.CreateModel(
            name='QualitativeScaleSublevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Escala Cualitativa por Subnivel',
                'verbose_name_plural': 'Escalas Cualitativas por Subnivel',
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pendiente de sincronizar'), ('PROCESSING', 'En procesamiento'), ('SYNCED', 'Sincronizado'), ('ERROR', 'Error de sincronización'), ('CONFLICT', 'Conflicto detectado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de Sincronización')),
                ('sync_version', models.PositiveIntegerField(default=1, verbose_name='Versión de Sincronización')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado en')),
                ('device_origin', models.CharField(blank=True, max_length=40, null=True, verbose_name='Dispositivo de Origen')),
                ('conflict_resolved', models.BooleanField(default=False, verbose_name='Conflicto Resuelto')),
                ('conflict_notes', models.TextField(blank=True, default='', verbose_name='Notas de Conflicto')),
                ('grading_mode', models.CharField(choices=[('NUMERIC', 'Cuantitativa'), ('QUALITATIVE', 'Cualitativa')], default='NUMERIC', help_text='Define si la nota es numérica o cualitativa', max_length=20, verbose_name='Modo de Calificación')),
                ('numeric_score', models.DecimalField(blank=True, decimal_places=2, help_text='Calificación numérica obtenida (escala 1-10)', max_digits=5, null=True, verbose_name='Puntuación Numérica')),
                ('manually_overridden', models.BooleanField(default=False, verbose_name='Anulada Manualmente')),
                ('teacher_observation', models.TextField(blank=True, default='', verbose_name='Observación del Docente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_notes_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Nota de Actividad',
                'verbose_name_plural': 'Notas de Actividades',
            },
        ),
    ]
