# Generated by Django 4.2.30 on 2026-06-16 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('grading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnote',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.enrollment', verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='evaluative_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.evaluativeactivity', verbose_name='Actividad Evaluativa'),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_notes_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='qualitative_scale',
            field=models.ForeignKey(blank=True, help_text='Escala cualitativa equivalente a la nota (si aplica)', null=True, on_delete=django.db.models.deletion.PROTECT, to='grading.qualitativescale', verbose_name='Escala Cualitativa'),
        ),
        migrations.AddField(
            model_name='qualitativescalesublevel',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublevel_links', to='grading.qualitativescale', verbose_name='Escala Cualitativa'),
        ),
        migrations.AddField(
            model_name='qualitativescalesublevel',
            name='sublevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scale_links', to='institutions.academicsublevel', verbose_name='Subnivel Académico'),
        ),
        migrations.AddField(
            model_name='periodgradesummary',
            name='academic_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_summaries', to='academic.academicperiod', verbose_name='Período Académico'),
        ),
        migrations.AddField(
            model_name='periodgradesummary',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_summaries_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='periodgradesummary',
            name='calculated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_summaries_calculated', to=settings.AUTH_USER_MODEL, verbose_name='Calculado por'),
        ),
        migrations.AddField(
            model_name='periodgradesummary',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_summaries', to='students.enrollment', verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='periodgradesummary',
            name='qualitative_scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='grading.qualitativescale', verbose_name='Escala Cualitativa'),
        ),
        migrations.AddField(
            model_name='periodgradesummary',
            name='subject_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_summaries', to='academic.subjectoffering', verbose_name='Oferta de Asignatura'),
        ),
        migrations.AddField(
            model_name='gradechangehistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_changes_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='gradechangehistory',
            name='modified_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='gradechangehistory',
            name='new_qualitative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_grade_changes', to='grading.qualitativescale', verbose_name='Nueva Escala Cualitativa'),
        ),
        migrations.AddField(
            model_name='gradechangehistory',
            name='previous_qualitative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_grade_changes', to='grading.qualitativescale', verbose_name='Escala Cualitativa Anterior'),
        ),
        migrations.AddField(
            model_name='gradechangehistory',
            name='student_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='grading.studentnote', verbose_name='Nota'),
        ),
        migrations.AddField(
            model_name='evaluativeactivity',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.activitytype', verbose_name='Tipo de Actividad'),
        ),
        migrations.AddField(
            model_name='evaluativeactivity',
            name='block_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='grading.blockcomponent', verbose_name='Componente de Bloque'),
        ),
        migrations.AddField(
            model_name='evaluativeactivity',
            name='teacher_subject_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluative_activities', to='academic.teachersubjectsection', verbose_name='Docente-Materia-Sección'),
        ),
        migrations.AddField(
            model_name='evaluationblock',
            name='academic_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_blocks', to='academic.academicperiod', verbose_name='Período Académico'),
        ),
        migrations.AddField(
            model_name='evaluationblock',
            name='subject_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_blocks', to='academic.subjectoffering', verbose_name='Oferta de Materia'),
        ),
        migrations.AddField(
            model_name='blockcomponent',
            name='evaluation_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='grading.evaluationblock', verbose_name='Bloque de Evaluación'),
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['enrollment', 'evaluative_activity'], name='grading_stu_enrollm_90708b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['evaluative_activity', 'numeric_score'], name='grading_stu_evaluat_c0b6f8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['sync_status'], name='grading_stu_sync_st_364ed8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['enrollment', 'sync_status'], name='grading_stu_enrollm_5bbef9_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentnote',
            constraint=models.UniqueConstraint(condition=models.Q(('evaluative_activity__isnull', False)), fields=('enrollment', 'evaluative_activity'), name='unique_enrollment_activity'),
        ),
        migrations.AlterUniqueTogether(
            name='qualitativescalesublevel',
            unique_together={('scale', 'sublevel')},
        ),
        migrations.AddIndex(
            model_name='periodgradesummary',
            index=models.Index(fields=['academic_period', 'subject_offering'], name='grading_per_academi_c25135_idx'),
        ),
        migrations.AddIndex(
            model_name='periodgradesummary',
            index=models.Index(fields=['enrollment', 'academic_period'], name='grading_per_enrollm_75aec0_idx'),
        ),
        migrations.AddIndex(
            model_name='periodgradesummary',
            index=models.Index(fields=['is_failing', 'academic_period'], name='grading_per_is_fail_adfada_idx'),
        ),
        migrations.AddConstraint(
            model_name='periodgradesummary',
            constraint=models.UniqueConstraint(fields=('enrollment', 'subject_offering', 'academic_period'), name='unique_period_grade_summary'),
        ),
        migrations.AddIndex(
            model_name='gradechangehistory',
            index=models.Index(fields=['student_note', 'modified_at'], name='grading_gra_student_432105_idx'),
        ),
        migrations.AddIndex(
            model_name='gradechangehistory',
            index=models.Index(fields=['modified_by_user', 'modified_at'], name='grading_gra_modifie_175ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluativeactivity',
            index=models.Index(fields=['teacher_subject_section', 'due_date'], name='grading_eva_teacher_c81388_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluativeactivity',
            index=models.Index(fields=['block_component', 'due_date'], name='grading_eva_block_c_a96b25_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationblock',
            index=models.Index(fields=['subject_offering', 'academic_period'], name='grading_eva_subject_612617_idx'),
        ),
    ]
