# Generated by Django 4.2.30 on 2026-06-10 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryProcessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Estado de Proceso de Recuperación',
                'verbose_name_plural': 'Estados de Procesos de Recuperación',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='qualitativescalesublevel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='recoveryprocesshistory',
            name='new_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_recovery', to='grading.recoveryprocessstatus', verbose_name='Nuevo Estado'),
        ),
        migrations.AlterField(
            model_name='recoveryprocesshistory',
            name='previous_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_recovery', to='grading.recoveryprocessstatus', verbose_name='Estado Anterior'),
        ),
    ]
