# Generated by Django 4.2.30 on 2026-06-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockcomponent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
