# Generated by Django 4.2.30 on 2026-06-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_blockcomponent_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluativeactivity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
