# Generated by Django 4.2.30 on 2026-06-26 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('academic_period', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pendiente de sincronizar'), ('PROCESSING', 'En procesamiento'), ('SYNCED', 'Sincronizado'), ('ERROR', 'Error de sincronización'), ('CONFLICT', 'Conflicto detectado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de Sincronización')),
                ('sync_version', models.PositiveIntegerField(default=1, verbose_name='Versión de Sincronización')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado en')),
                ('device_origin', models.CharField(blank=True, max_length=40, null=True, verbose_name='Dispositivo de Origen')),
                ('conflict_resolved', models.BooleanField(default=False, verbose_name='Conflicto Resuelto')),
                ('conflict_notes', models.TextField(blank=True, default='', verbose_name='Notas de Conflicto')),
                ('alert_type', models.CharField(blank=True, choices=[('low_attendance', 'Baja Asistencia'), ('failing_grades', 'Calificaciones Bajas'), ('behavioral', 'Problemas de Conducta'), ('dropout_risk', 'Riesgo de Deserción'), ('socioemotional', 'Problemas Socioemocionales')], max_length=30, null=True, verbose_name='Tipo de alerta')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('urgency_level', models.CharField(blank=True, choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=20, null=True, verbose_name='Nivel de urgencia')),
                ('attended', models.BooleanField(default=False, verbose_name='Atendida')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de detección')),
                ('attended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de atención')),
                ('response_actions', models.TextField(blank=True, default='', verbose_name='Acciones de respuesta')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_alerts', to='academic_period.academicperiod', verbose_name='Período Académico')),
                ('attended_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Atendida por')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_alerts', to='students.enrollment', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Alerta Temprana',
                'verbose_name_plural': 'Alertas Tempranas',
                'db_table': 'analytics_earlyalert',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['attended', 'urgency_level'], name='analytics_e_attende_b372a7_idx'), models.Index(fields=['enrollment', 'academic_period'], name='analytics_e_enrollm_64cad3_idx')],
            },
        ),
    ]
