# Generated by Django 4.2.30 on 2026-07-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early_alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlyalert',
            name='sync_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de sincronizar'), ('PROCESSING', 'En procesamiento'), ('SYNCED', 'Sincronizado'), ('ERROR', 'Error de sincronización'), ('CONFLICT', 'Conflicto detectado'), ('ROLLED_BACK', 'Revertido')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de Sincronización'),
        ),
    ]
