# Generated by Django 4.2.30 on 2026-05-17 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Nivel')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Nivel Académico',
                'verbose_name_plural': 'Niveles Académicos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Sala',
                'verbose_name_plural': 'Tipos de Sala',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='School_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Año Escolar')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Año Escolar',
                'verbose_name_plural': 'Años Escolares',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Salón')),
                ('capacity', models.IntegerField(verbose_name='Capacidad')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.roomtype', verbose_name='Tipo de Sala')),
            ],
            options={
                'verbose_name': 'Salón',
                'verbose_name_plural': 'Salones',
            },
        ),
        migrations.CreateModel(
            name='AcademicGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Grado')),
                ('sequence_order', models.IntegerField(verbose_name='Orden')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('academic_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.academiclevel', verbose_name='Nivel Académico')),
            ],
            options={
                'verbose_name': 'Grado Académico',
                'verbose_name_plural': 'Grados Académicos',
                'ordering': ['sequence_order'],
            },
        ),
    ]
