# Generated by Django 4.2.30 on 2026-06-09 00:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Grado')),
                ('sequence_order', models.IntegerField(verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Grado Académico',
                'verbose_name_plural': 'Grados Académicos',
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Nivel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Nivel Académico',
                'verbose_name_plural': 'Niveles Académicos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Año Escolar')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Año Escolar',
                'verbose_name_plural': 'Años Escolares',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Código')),
                ('parallel', models.CharField(max_length=255, verbose_name='Paralelo')),
                ('capacity', models.IntegerField(verbose_name='Capacidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('academic_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.academicgrade', verbose_name='Grado Académico')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.schoolyear', verbose_name='Año Escolar')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.CreateModel(
            name='AcademicSublevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('academic_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublevels', to='institutions.academiclevel', verbose_name='Nivel Académico')),
            ],
            options={
                'verbose_name': 'Subnivel Académico',
                'verbose_name_plural': 'Subniveles Académicos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='academicgrade',
            name='academic_sublevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.academicsublevel', verbose_name='Subnivel Académico'),
        ),
    ]
