# Generated by Django 4.2.30 on 2026-05-10 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='Sincronizado desde Person.email', max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es Personal del Admin')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Es Superusuario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Formato: '<app>.<acción>', ej: 'grading.create_note'", max_length=100, unique=True, verbose_name='Código del Permiso')),
                ('description', models.CharField(blank=True, help_text='Descripción legible del permiso', max_length=255, verbose_name='Descripción')),
                ('module', models.CharField(blank=True, help_text='Módulo asociado (grading, academic, etc)', max_length=50, verbose_name='Módulo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('names', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_names', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['last_names', 'names'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre único del rol', max_length=100, unique=True, verbose_name='Nombre del Rol')),
                ('code', models.CharField(help_text='Código único del rol (DOCENTE, ADMIN, etc)', max_length=50, null=True, unique=True, verbose_name='Código del Rol')),
                ('description', models.CharField(blank=True, help_text='Descripción del rol', max_length=255, verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, help_text='Indica si el rol puede ser asignado a nuevos usuarios', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Asignado en')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira en')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='accounts.role', verbose_name='Rol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Rol del Usuario',
                'verbose_name_plural': 'Roles del Usuario',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=True, help_text='Verdadero = otorgado, Falso = revocado', verbose_name='Otorgado')),
                ('reason', models.TextField(blank=True, help_text='Razón del cambio de permiso (auditoría)', verbose_name='Razón')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración del permiso (opcional)', null=True, verbose_name='Fecha de Expiración')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('granted_by', models.ForeignKey(blank=True, help_text='Usuario que otorgó/revocó este permiso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_user_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Otorgado por')),
                ('permission', models.ForeignKey(help_text='El permiso otorgado o revocado', on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions_set', to='accounts.permission', verbose_name='Permiso')),
                ('user', models.ForeignKey(help_text='Usuario al que se aplica el permiso', on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions_set', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso del Usuario',
                'verbose_name_plural': 'Permisos del Usuario',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('permission', models.ForeignKey(help_text='El permiso otorgado', on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='accounts.permission', verbose_name='Permiso')),
                ('role', models.ForeignKey(help_text='El rol que recibe el permiso', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Permiso del Rol',
                'verbose_name_plural': 'Permisos del Rol',
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='accounts_ro_name_183ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['active'], name='accounts_ro_active_396d91_idx'),
        ),
        migrations.AddField(
            model_name='person',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.documenttype', verbose_name='Tipo de Documento'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['code'], name='accounts_pe_code_3a265a_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['module'], name='accounts_pe_module_1658a5_idx'),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='institutions.institution', verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='user',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.person', verbose_name='Persona'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user'], name='accounts_us_user_id_e1cd7b_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['permission'], name='accounts_us_permiss_db730c_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['granted'], name='accounts_us_granted_4eecde_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('user', 'permission')},
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role'], name='accounts_ro_role_id_71b0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission'], name='accounts_ro_permiss_bf7476_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['document_number'], name='accounts_pe_documen_71b5f8_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['active'], name='accounts_pe_active_60ea9f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['active'], name='accounts_us_active_8a031a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['institution'], name='accounts_us_institu_8662a0_idx'),
        ),
    ]
