# Generated by Django 6.0.4 on 2026-04-30 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text="Formato: '<app>.<accion>', ej: 'grading.create_note'", max_length=100, unique=True)),
                ('description', models.CharField(blank=True, help_text='Descripción legible del permiso', max_length=255)),
                ('module', models.CharField(blank=True, help_text='Módulo asociado (grading, academic, etc)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['codename'],
                'indexes': [models.Index(fields=['codename'], name='accounts_pe_codenam_3517e8_idx'), models.Index(fields=['module'], name='accounts_pe_module_1658a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre único del rol (Docente, Admin, Director, etc)', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, help_text='Descripción del rol', max_length=255)),
                ('active', models.BooleanField(default=True, help_text='Indica si el rol puede ser asignado a nuevos usuarios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='accounts_ro_name_183ba5_idx'), models.Index(fields=['active'], name='accounts_ro_active_396d91_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('dni', models.CharField(help_text='Documento de identidad', max_length=20, unique=True)),
                ('names', models.CharField(help_text='Nombres del usuario', max_length=100)),
                ('last_names', models.CharField(help_text='Apellidos del usuario', max_length=100)),
                ('email', models.EmailField(help_text='Correo electrónico único', max_length=254, unique=True)),
                ('active', models.BooleanField(default=True, help_text='Indica si el usuario puede acceder al sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(help_text='Institución a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='institutions.institution')),
                ('role', models.ForeignKey(help_text='Rol asignado al usuario', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(help_text='El permiso otorgado', on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='accounts.permission')),
                ('role', models.ForeignKey(help_text='El rol que recibe el permiso', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role')),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=True, help_text='True = otorgado, False = revocado')),
                ('reason', models.TextField(blank=True, help_text='Razón del cambio de permiso (auditoría)')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración del permiso (opcional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, help_text='Usuario que otorgó/revocó este permiso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_user_permissions', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(help_text='El permiso otorgado o revocado', on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions_set', to='accounts.permission')),
                ('user', models.ForeignKey(help_text='Usuario al que se aplica el permiso', on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['dni'], name='accounts_us_dni_493334_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['active'], name='accounts_us_active_8a031a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['institution'], name='accounts_us_institu_8662a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('dni', 'institution')},
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role'], name='accounts_ro_role_id_71b0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission'], name='accounts_ro_permiss_bf7476_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user'], name='accounts_us_user_id_e1cd7b_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['permission'], name='accounts_us_permiss_db730c_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['granted'], name='accounts_us_granted_4eecde_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('user', 'permission')},
        ),
    ]
