# Generated by Django 4.2.30 on 2026-07-07 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Parroquia')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código de la Parroquia')),
                ('parish_type', models.CharField(choices=[('URBANA', 'Urbana'), ('RURAL', 'Rural')], max_length=10, verbose_name='Tipo de Parroquia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.city', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Parroquia',
                'verbose_name_plural': 'Parroquias',
                'db_table': 'people_parish',
                'ordering': ['name'],
            },
        ),
    ]
