# Generated by Django 4.2.30 on 2026-07-07 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_parish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.AddField(
            model_name='person',
            name='parish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='people.parish', verbose_name='Parroquia de Residencia'),
        ),
    ]
