# Generated by Django 4.2.30 on 2026-06-24 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_subject_config', '0001_initial'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_offerings', to='institutions.section', verbose_name='Sección')),
                ('subject_academic_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academic_subject_config.subjectacademicconfig', verbose_name='Configuración de Materia')),
            ],
            options={
                'verbose_name': 'Oferta de Materia',
                'verbose_name_plural': 'Ofertas de Materias',
            },
        ),
        migrations.AddConstraint(
            model_name='subjectoffering',
            constraint=models.UniqueConstraint(fields=('section', 'subject_academic_config'), name='unique_section_subject_config'),
        ),
    ]
