# Generated by Django 4.2.30 on 2026-06-24 02:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('divisions_per_year', models.PositiveSmallIntegerField(default=1, help_text='Cantidad de veces que el año escolar se divide con este tipo de período (ej: 3 para Trimestre, 2 para Semestre, 4 para Bimestre).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Divisiones por año')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Período',
                'verbose_name_plural': 'Tipos de Período',
                'ordering': ['name'],
            },
        ),
    ]
