# Generated by Django 4.2.30 on 2026-06-24 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions_academic_sublevel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualitativeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('numeric_equivalence', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Equivalencia Numérica')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Escala Cualitativa',
                'verbose_name_plural': 'Escalas Cualitativas',
                'ordering': ['-numeric_equivalence'],
            },
        ),
        migrations.CreateModel(
            name='QualitativeScaleSublevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublevel_links', to='grading_qualitative_scale.qualitativescale', verbose_name='Escala Cualitativa')),
                ('sublevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scale_links', to='institutions_academic_sublevel.academicsublevel', verbose_name='Subnivel Académico')),
            ],
            options={
                'verbose_name': 'Escala Cualitativa por Subnivel',
                'verbose_name_plural': 'Escalas Cualitativas por Subnivel',
                'unique_together': {('scale', 'sublevel')},
            },
        ),
    ]
