# Generated by Django 4.2 on 2026-06-28 23:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("grading_qualitative_scale", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QualitativeScaleSublevel",
        ),
    ]
