# Generated by Django 4.2.30 on 2026-06-16 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name='Clave de Idempotencia')),
                ('source_table', models.CharField(max_length=100, verbose_name='Tabla Origen')),
                ('record_uuid', models.CharField(max_length=36, verbose_name='UUID del Registro')),
                ('operation', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar')], max_length=20, verbose_name='Operación')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('previous_state', models.JSONField(blank=True, default=dict, verbose_name='Estado Anterior')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Intentos')),
                ('max_attempts', models.PositiveIntegerField(default=5, verbose_name='Máximo de Intentos')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Último Error')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Intento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de sincronizar'), ('PROCESSING', 'En procesamiento'), ('SYNCED', 'Sincronizado'), ('ERROR', 'Error de sincronización'), ('CONFLICT', 'Conflicto detectado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado')),
                ('conflict_detected', models.BooleanField(default=False, verbose_name='Conflicto Detectado')),
                ('resolution_strategy', models.CharField(blank=True, max_length=30, null=True, verbose_name='Estrategia de Resolución')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Procesada en')),
                ('resolution_notes', models.TextField(blank=True, default='', verbose_name='Notas de resolución')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_processed', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_resolved', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario origen')),
            ],
            options={
                'verbose_name': 'Cola de Sincronización',
                'verbose_name_plural': 'Cola de Sincronización',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='integration_status_6249d1_idx'), models.Index(fields=['source_table', 'record_uuid'], name='integration_source__7dfa7a_idx'), models.Index(fields=['user', 'status'], name='integration_user_id_14ba5d_idx'), models.Index(fields=['conflict_detected', 'status'], name='integration_conflic_157ce9_idx')],
            },
        ),
    ]
