# Generated by Django 4.2.30 on 2026-06-09 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Operación de Sincronización',
                'verbose_name_plural': 'Operaciones de Sincronización',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncSchemaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('model_name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del modelo')),
                ('schema_version', models.PositiveIntegerField(default=1, verbose_name='Versión del esquema')),
                ('fields_hash', models.CharField(max_length=64, verbose_name='Hash de campos')),
                ('min_client_version', models.CharField(default='1.0.0', max_length=20, verbose_name='Versión mínima de cliente')),
            ],
            options={
                'verbose_name': 'Versión de Esquema de Sincronización',
                'verbose_name_plural': 'Versiones de Esquema de Sincronización',
                'ordering': ['model_name'],
            },
        ),
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Estado de Sincronización',
                'verbose_name_plural': 'Estados de Sincronización',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name='Clave de Idempotencia')),
                ('source_table', models.CharField(max_length=100, verbose_name='Tabla Origen')),
                ('record_uuid', models.CharField(max_length=36, verbose_name='UUID del Registro')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('previous_state', models.JSONField(blank=True, default=dict, verbose_name='Estado Anterior')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Intentos')),
                ('max_attempts', models.PositiveIntegerField(default=5, verbose_name='Máximo de Intentos')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='Último Error')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Intento')),
                ('conflict_detected', models.BooleanField(default=False, verbose_name='Conflicto Detectado')),
                ('resolution_strategy', models.CharField(blank=True, max_length=30, null=True, verbose_name='Estrategia de Resolución')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Procesada en')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='Notas de resolución')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integration.syncoperation', verbose_name='Operación')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_processed', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_resolved', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='integration.syncstatus', verbose_name='Estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario origen')),
            ],
            options={
                'verbose_name': 'Cola de Sincronización',
                'verbose_name_plural': 'Cola de Sincronización',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='integration_status__ab152b_idx'), models.Index(fields=['source_table', 'record_uuid'], name='integration_source__7dfa7a_idx'), models.Index(fields=['user', 'status'], name='integration_user_id_50c1ce_idx'), models.Index(fields=['conflict_detected', 'status'], name='integration_conflic_9caa16_idx')],
            },
        ),
    ]
