# Generated by Django 4.2.30 on 2026-06-09 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Operación de Sincronización',
                'verbose_name_plural': 'Operaciones de Sincronización',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Estado de Sincronización',
                'verbose_name_plural': 'Estados de Sincronización',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('source_table', models.CharField(max_length=100, verbose_name='Tabla Origen')),
                ('record_uuid', models.CharField(max_length=36, verbose_name='UUID del Registro')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Intentos')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='Último Error')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Procesada en')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integration.syncoperation', verbose_name='Operación')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='integration.syncstatus', verbose_name='Estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario origen')),
            ],
            options={
                'verbose_name': 'Cola de Sincronización',
                'verbose_name_plural': 'Cola de Sincronización',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='integration_status__ab152b_idx'), models.Index(fields=['source_table', 'record_uuid'], name='integration_source__7dfa7a_idx'), models.Index(fields=['user', 'status'], name='integration_user_id_50c1ce_idx')],
            },
        ),
    ]
