# Generated by Django 4.2.30 on 2026-07-15 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncqueue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de sincronizar'), ('PROCESSING', 'En procesamiento'), ('SYNCED', 'Sincronizado'), ('ERROR', 'Error de sincronización'), ('CONFLICT', 'Conflicto detectado'), ('ROLLED_BACK', 'Revertido')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='SyncBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('client_batch_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='ID del lote (cliente)')),
                ('status', models.CharField(choices=[('RECEIVED', 'Recibido'), ('QUEUED', 'Encolado'), ('PROCESSING', 'En procesamiento'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('ROLLED_BACK', 'Revertido')], db_index=True, default='RECEIVED', max_length=20, verbose_name='Estado del lote')),
                ('total_operations', models.PositiveIntegerField(default=0, verbose_name='Total de operaciones')),
                ('completed_operations', models.PositiveIntegerField(default=0, verbose_name='Operaciones completadas')),
                ('failed_operations', models.PositiveIntegerField(default=0, verbose_name='Operaciones fallidas')),
                ('committed', models.BooleanField(default=False, verbose_name='Transacción commiteada')),
                ('cached_response', models.JSONField(blank=True, default=dict, verbose_name='Respuesta cacheada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario origen')),
            ],
            options={
                'verbose_name': 'Lote de Sincronización',
                'verbose_name_plural': 'Lotes de Sincronización',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='integration.syncbatch', verbose_name='Lote'),
        ),
    ]
