# Generated by Django 4.2.30 on 2026-06-26 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_subject_offering', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academic_subject_offering.subjectoffering', verbose_name='Oferta de Materia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Docente-Materia-Sección',
                'verbose_name_plural': 'Docentes-Materias-Secciones',
                'indexes': [models.Index(fields=['user', 'is_active'], name='academic_te_user_id_4f8b78_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='teachersubjectsection',
            constraint=models.UniqueConstraint(fields=('user', 'subject_offering'), name='unique_teacher_subject'),
        ),
    ]
