# Generated by Django 4.2.30 on 2026-06-26 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kinship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Parentesco',
                'verbose_name_plural': 'Parentescos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialNeedsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Necesidad Especial',
                'verbose_name_plural': 'Tipos de Necesidades Especiales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('student_code', models.CharField(max_length=50, unique=True, verbose_name='Código de Estudiante')),
                ('has_special_needs', models.BooleanField(default=False, verbose_name='Tiene Necesidades Educativas Especiales (NEE)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('special_needs_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.specialneedstype', verbose_name='Tipo de NEE')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Motivo de Retiro',
                'verbose_name_plural': 'Motivos de Retiro',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Es Principal')),
                ('emergency_contact', models.BooleanField(default=False, verbose_name='Contacto de Emergencia')),
                ('receives_notifications', models.BooleanField(default=True, verbose_name='Recibe Notificaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('kinship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.kinship', verbose_name='Parentesco')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives_set', to='students.student', verbose_name='Estudiante')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_representatives', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Representante')),
            ],
            options={
                'verbose_name': 'Relación Estudiante-Representante',
                'verbose_name_plural': 'Relaciones Estudiante-Representante',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pendiente de sincronizar'), ('PROCESSING', 'En procesamiento'), ('SYNCED', 'Sincronizado'), ('ERROR', 'Error de sincronización'), ('CONFLICT', 'Conflicto detectado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de Sincronización')),
                ('sync_version', models.PositiveIntegerField(default=1, verbose_name='Versión de Sincronización')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado en')),
                ('device_origin', models.CharField(blank=True, max_length=40, null=True, verbose_name='Dispositivo de Origen')),
                ('conflict_resolved', models.BooleanField(default=False, verbose_name='Conflicto Resuelto')),
                ('conflict_notes', models.TextField(blank=True, default='', verbose_name='Notas de Conflicto')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Matrícula')),
                ('enrollment_status', models.CharField(choices=[('ACT', 'Activa'), ('RET', 'Retirado'), ('TRS', 'Transferido'), ('SUS', 'Suspendido'), ('GRA', 'Graduado'), ('INA', 'Inactivo')], max_length=5, verbose_name='Estado de Matrícula')),
                ('withdrawal_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Retiro')),
                ('is_repeat', models.BooleanField(default=False, verbose_name='Es repitente')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='institutions_section.section', verbose_name='Sección')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='Estudiante')),
                ('withdrawal_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.withdrawalreason', verbose_name='Motivo de Retiro')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.AddConstraint(
            model_name='studentrepresentative',
            constraint=models.UniqueConstraint(fields=('student', 'user'), name='unique_student_user'),
        ),
        migrations.AddConstraint(
            model_name='studentrepresentative',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('student',), name='unique_primary_representative_per_student'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_code'], name='students_st_student_5e7a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'enrollment_status'], name='students_en_student_a8a5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['section', 'enrollment_status'], name='students_en_section_f0e4a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'section'), name='unique_student_section'),
        ),
    ]
