# Generated by Django 6.0.4 on 2026-04-30 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('last_names', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=13, unique=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_names', 'names'],
                'indexes': [models.Index(fields=['dni'], name='students_re_dni_e56506_idx'), models.Index(fields=['active'], name='students_re_active_78e249_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dni', models.CharField(max_length=13, unique=True)),
                ('names', models.CharField(max_length=100)),
                ('last_names', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('enrollment_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('sync_status', models.CharField(default='pending', max_length=20)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=0)),
                ('device_origin', models.CharField(blank=True, max_length=40, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academic.section')),
            ],
            options={
                'ordering': ['last_names', 'names'],
            },
        ),
        migrations.CreateModel(
            name='Student_Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinship', models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Abuelo/a', 'Abuelo/a'), ('Tío/a', 'Tío/a'), ('Hermano/a Mayor', 'Hermano/a Mayor'), ('Otro', 'Otro')], default='Padre', max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('can_pickup', models.BooleanField(default=True)),
                ('emergency_contact', models.BooleanField(default=False)),
                ('receives_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_set', to='students.representative')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives_set', to='students.student')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['dni'], name='students_st_dni_e945e0_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['section', 'active'], name='students_st_section_b29272_idx'),
        ),
        migrations.AddIndex(
            model_name='student_representative',
            index=models.Index(fields=['student', 'is_primary'], name='students_st_student_3c9f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='student_representative',
            index=models.Index(fields=['representative'], name='students_st_represe_ba2c15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='student_representative',
            unique_together={('student', 'representative')},
        ),
    ]
