# Generated by Django 4.2.30 on 2026-05-10 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, default='', max_length=100)),
                ('last_names', models.CharField(blank=True, default='', max_length=100)),
                ('dni', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'students_representative',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnrollmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Estado de Matrícula',
                'verbose_name_plural': 'Estados de Matrícula',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=50, unique=True, verbose_name='Código de Estudiante')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.person', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Matrícula')),
                ('sync_status', models.CharField(default='pending', max_length=20, verbose_name='Estado de Sincronización')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('sync_version', models.PositiveIntegerField(default=0, verbose_name='Versión de Sincronización')),
                ('device_origin', models.CharField(blank=True, max_length=40, null=True, verbose_name='Dispositivo de Origen')),
                ('enrollment_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.enrollmentstatus', verbose_name='Estado de Matrícula')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.section', verbose_name='Sección')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.CreateModel(
            name='Student_Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinship', models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Abuelo/a', 'Abuelo/a'), ('Tío/a', 'Tío/a'), ('Hermano/a Mayor', 'Hermano/a Mayor'), ('Otro', 'Otro')], default='Padre', max_length=30, verbose_name='Parentesco')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Es Principal')),
                ('can_pickup', models.BooleanField(default=True, verbose_name='Puede Recoger')),
                ('emergency_contact', models.BooleanField(default=False, verbose_name='Contacto de Emergencia')),
                ('receives_notifications', models.BooleanField(default=True, verbose_name='Recibe Notificaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_representatives', to='accounts.person', verbose_name='Persona')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives_set', to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Relación Estudiante-Representante',
                'verbose_name_plural': 'Relaciones Estudiante-Representante',
                'ordering': ['-is_primary', '-created_at'],
                'unique_together': {('student', 'person')},
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_code'], name='students_st_student_5e7a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'enrollment_status'], name='students_en_student_9b0aed_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['section', 'enrollment_status'], name='students_en_section_46143c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'section')},
        ),
    ]
