# Generated by Django 4.2.30 on 2026-06-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_status',
            field=models.CharField(choices=[('ACT', 'Activa'), ('RET', 'Retirado'), ('TRS', 'Transferido'), ('SUS', 'Suspendido'), ('GRA', 'Graduado'), ('INA', 'Inactivo')], max_length=5, verbose_name='Estado de Matrícula'),
        ),
    ]
