# Generated by Django 4.2.30 on 2026-06-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Nivel')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Codigo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Nivel Academico',
                'verbose_name_plural': 'Niveles Academicos',
                'ordering': ['name'],
            },
        ),
    ]
