# Generated by Django 4.2.30 on 2026-06-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions_academic_level', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiclevel',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
