# Generated by Django 4.2.30 on 2026-06-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions_academic_level', '0002_add_description_to_academiclevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiclevel',
            name='code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Codigo'),
        ),
    ]
