# Generated by Django 4.2.30 on 2026-06-16 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Modificación'), ('DELETE', 'Eliminación'), ('RECOVER', 'Recuperación')], max_length=20, verbose_name='Acción')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modelo')),
                ('record_id', models.CharField(max_length=36, verbose_name='ID del Registro')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Cambios')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Bitácora de Auditoría',
                'verbose_name_plural': 'Bitácoras de Auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'record_id'], name='core_auditl_model_n_ec57af_idx'), models.Index(fields=['user', '-created_at'], name='core_auditl_user_id_969660_idx'), models.Index(fields=['action', '-created_at'], name='core_auditl_action_d80c2d_idx')],
            },
        ),
    ]
