# Generated by Django 4.2.30 on 2026-05-30 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Clave')),
                ('value', models.TextField(verbose_name='Valor')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID único de esta operación de sincronización', unique=True, verbose_name='UUID')),
                ('source_table', models.CharField(help_text='Nombre de la tabla que originó la operación pendiente', max_length=100, verbose_name='Tabla Origen')),
                ('record_uuid', models.CharField(help_text='UUID del registro en la tabla de origen', max_length=36, verbose_name='UUID del Registro')),
                ('operation', models.CharField(choices=[('INSERT', 'Insertar'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar')], help_text='Tipo de operación pendiente: INSERT, UPDATE o DELETE', max_length=10, verbose_name='Operación')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Datos completos del registro a sincronizar en formato JSON', verbose_name='Payload')),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Número de intentos fallidos de sincronización', verbose_name='Intentos')),
                ('last_error', models.TextField(blank=True, help_text='Descripción del último error de sincronización', null=True, verbose_name='Último Error')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESADO', 'Procesado'), ('ERROR', 'Error')], default='PENDIENTE', help_text='Estado actual de la operación: PENDIENTE, PROCESADO o ERROR', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se generó la operación offline', verbose_name='Creada en')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que fue procesada exitosamente', null=True, verbose_name='Procesada en')),
                ('user', models.ForeignKey(help_text='Usuario que originó la operación offline', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario origen')),
            ],
            options={
                'verbose_name': 'Cola de Sincronización',
                'verbose_name_plural': 'Cola de Sincronización',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_syncqu_status_78ab07_idx'), models.Index(fields=['source_table', 'record_uuid'], name='core_syncqu_source__11f5f8_idx'), models.Index(fields=['user', 'status'], name='core_syncqu_user_id_5d5aa2_idx')],
            },
        ),
    ]
