# Generated by Django 4.2.30 on 2026-06-28 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('notification_type', models.CharField(choices=[('ACTIVITY_CREATED', 'Actividad creada'), ('ACTIVITY_GRADED', 'Actividad calificada'), ('ATTENDANCE_CREATED', 'Asistencia registrada'), ('INCIDENT_CREATED', 'Incidente de conducta')], max_length=30, verbose_name='Tipo de Notificación')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('body', models.TextField(blank=True, default='', verbose_name='Cuerpo')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Datos')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída en')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='core_notifi_recipie_4d7e73_idx'), models.Index(fields=['recipient', 'is_read'], name='core_notifi_recipie_aeffaf_idx')],
            },
        ),
    ]
