# Generated by Django 4.2.30 on 2026-06-09 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Clave')),
                ('value', models.TextField(verbose_name='Valor')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
