# Generated by Django 4.2.30 on 2026-06-26 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions_academic_level', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSublevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('academic_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublevels', to='institutions_academic_level.academiclevel', verbose_name='Nivel Academico')),
            ],
            options={
                'verbose_name': 'Subnivel Academico',
                'verbose_name_plural': 'Subniveles Academicos',
                'ordering': ['name'],
            },
        ),
    ]
