# Generated by Django 4.2.30 on 2026-06-09 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Incidente',
                'verbose_name_plural': 'Tipos de Incidente',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SocioemotionalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Habilidad Socioemocional',
                'verbose_name_plural': 'Habilidades Socioemocionales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('socioemotional_area', models.CharField(max_length=100, verbose_name='Área socioemocional')),
                ('findings_description', models.TextField(verbose_name='Descripción de hallazgos')),
                ('development_level', models.CharField(max_length=50, verbose_name='Nivel de desarrollo')),
                ('application_date', models.DateField(verbose_name='Fecha de aplicación')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Recomendaciones')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_evaluations', to='academic.academicperiod', verbose_name='Período Académico')),
                ('applied_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Aplicada por')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_evaluations', to='students.enrollment', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Evaluación Diagnóstica',
                'verbose_name_plural': 'Evaluaciones Diagnósticas',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='ConductIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('incident_date', models.DateField(verbose_name='Fecha del Incidente')),
                ('severity', models.IntegerField(verbose_name='Gravedad')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('actions_taken', models.TextField(blank=True, null=True, verbose_name='Acciones tomadas')),
                ('family_notified', models.BooleanField(default=False, verbose_name='Familia Notificada')),
                ('sync_status', models.CharField(default='pending', max_length=20, verbose_name='Estado de Sincronización')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado el')),
                ('sync_version', models.PositiveIntegerField(default=0, verbose_name='Versión de Sincronización')),
                ('device_origin', models.CharField(blank=True, max_length=40, null=True, verbose_name='Dispositivo de Origen')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_incidents', to='academic.academicperiod', verbose_name='Período Académico')),
                ('enrollment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conduct_incidents', to='students.enrollment', verbose_name='Matrícula')),
                ('incident_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='behavior.incidenttype', verbose_name='Tipo de incidente')),
                ('reported_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_conduct_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Incidente de Conducta',
                'verbose_name_plural': 'Incidentes de Conducta',
            },
        ),
        migrations.CreateModel(
            name='SkillEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('evaluation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Evaluación')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evaluations', to='academic.academicperiod', verbose_name='Período Académico')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evaluations', to='students.enrollment', verbose_name='Matrícula')),
                ('qualitative_scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grading.qualitativescale', verbose_name='Escala Cualitativa')),
                ('socioemotional_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='behavior.socioemotionalskill', verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Evaluación de Habilidad',
                'verbose_name_plural': 'Evaluaciones de Habilidades',
                'unique_together': {('enrollment', 'academic_period', 'socioemotional_skill')},
            },
        ),
        migrations.CreateModel(
            name='BehaviorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('general_observation', models.TextField(blank=True, null=True, verbose_name='Observación general')),
                ('override_reason', models.TextField(blank=True, null=True, verbose_name='Razón de anulación')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_behavior_evaluations', to='academic.academicperiod', verbose_name='Período Académico')),
                ('calculated_scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_calculated_evaluations', to='grading.qualitativescale', verbose_name='Escala Calculada')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_behavior_evaluations', to='students.enrollment', verbose_name='Matrícula')),
                ('final_scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_final_evaluations', to='grading.qualitativescale', verbose_name='Escala Final')),
            ],
            options={
                'verbose_name': 'Evaluación de Conducta',
                'verbose_name_plural': 'Evaluaciones de Conducta',
                'unique_together': {('enrollment', 'academic_period')},
            },
        ),
    ]
