# Generated by Django 4.2.30 on 2026-06-09 05:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grading', '0001_initial'),
        ('academic', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Nivel de Desarrollo',
                'verbose_name_plural': 'Niveles de Desarrollo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Incidente',
                'verbose_name_plural': 'Tipos de Incidente',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('numeric_level', models.IntegerField(verbose_name='Nivel Numérico')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Severidad',
                'verbose_name_plural': 'Severidades',
                'ordering': ['numeric_level'],
            },
        ),
        migrations.CreateModel(
            name='SocioemotionalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Área Socioemocional',
                'verbose_name_plural': 'Áreas Socioemocionales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SocioemotionalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Habilidad Socioemocional',
                'verbose_name_plural': 'Habilidades Socioemocionales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pendiente de sincronizar'), ('PROCESSING', 'En procesamiento'), ('SYNCED', 'Sincronizado'), ('ERROR', 'Error de sincronización'), ('CONFLICT', 'Conflicto detectado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de Sincronización')),
                ('sync_version', models.PositiveIntegerField(default=1, verbose_name='Versión de Sincronización')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado en')),
                ('device_origin', models.CharField(blank=True, max_length=40, null=True, verbose_name='Dispositivo de Origen')),
                ('conflict_resolved', models.BooleanField(default=False, verbose_name='Conflicto Resuelto')),
                ('conflict_notes', models.TextField(blank=True, null=True, verbose_name='Notas de Conflicto')),
                ('findings_description', models.TextField(verbose_name='Descripción de hallazgos')),
                ('application_date', models.DateField(verbose_name='Fecha de aplicación')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Recomendaciones')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_evaluations', to='academic.academicperiod', verbose_name='Período Académico')),
                ('applied_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Aplicada por')),
                ('development_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='behavior.developmentlevel', verbose_name='Nivel de Desarrollo')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_evaluations', to='students.enrollment', verbose_name='Matrícula')),
                ('socioemotional_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='behavior.socioemotionalarea', verbose_name='Área Socioemocional')),
            ],
            options={
                'verbose_name': 'Evaluación Diagnóstica',
                'verbose_name_plural': 'Evaluaciones Diagnósticas',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='SkillEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pendiente de sincronizar'), ('PROCESSING', 'En procesamiento'), ('SYNCED', 'Sincronizado'), ('ERROR', 'Error de sincronización'), ('CONFLICT', 'Conflicto detectado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de Sincronización')),
                ('sync_version', models.PositiveIntegerField(default=1, verbose_name='Versión de Sincronización')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado en')),
                ('device_origin', models.CharField(blank=True, max_length=40, null=True, verbose_name='Dispositivo de Origen')),
                ('conflict_resolved', models.BooleanField(default=False, verbose_name='Conflicto Resuelto')),
                ('conflict_notes', models.TextField(blank=True, null=True, verbose_name='Notas de Conflicto')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('evaluation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Evaluación')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evaluations', to='academic.academicperiod', verbose_name='Período Académico')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evaluations', to='students.enrollment', verbose_name='Matrícula')),
                ('qualitative_scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grading.qualitativescale', verbose_name='Escala Cualitativa')),
                ('socioemotional_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='behavior.socioemotionalskill', verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Evaluación de Habilidad',
                'verbose_name_plural': 'Evaluaciones de Habilidades',
                'indexes': [models.Index(fields=['academic_period', 'socioemotional_skill'], name='behavior_sk_academi_83ba22_idx')],
                'unique_together': {('enrollment', 'academic_period', 'socioemotional_skill')},
            },
        ),
        migrations.CreateModel(
            name='ConductIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pendiente de sincronizar'), ('PROCESSING', 'En procesamiento'), ('SYNCED', 'Sincronizado'), ('ERROR', 'Error de sincronización'), ('CONFLICT', 'Conflicto detectado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de Sincronización')),
                ('sync_version', models.PositiveIntegerField(default=1, verbose_name='Versión de Sincronización')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado en')),
                ('device_origin', models.CharField(blank=True, max_length=40, null=True, verbose_name='Dispositivo de Origen')),
                ('conflict_resolved', models.BooleanField(default=False, verbose_name='Conflicto Resuelto')),
                ('conflict_notes', models.TextField(blank=True, null=True, verbose_name='Notas de Conflicto')),
                ('incident_date', models.DateField(verbose_name='Fecha del Incidente')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('actions_taken', models.TextField(blank=True, null=True, verbose_name='Acciones tomadas')),
                ('family_notified', models.BooleanField(default=False, verbose_name='Familia Notificada')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_incidents', to='academic.academicperiod', verbose_name='Período Académico')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('enrollment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conduct_incidents', to='students.enrollment', verbose_name='Matrícula')),
                ('incident_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='behavior.incidenttype', verbose_name='Tipo de incidente')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('reported_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_conduct_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='behavior.severity', verbose_name='Severidad')),
            ],
            options={
                'verbose_name': 'Incidente de Conducta',
                'verbose_name_plural': 'Incidentes de Conducta',
                'ordering': ['-incident_date'],
                'indexes': [models.Index(fields=['enrollment', 'academic_period'], name='behavior_co_enrollm_beb9d1_idx'), models.Index(fields=['academic_period', 'severity'], name='behavior_co_academi_328217_idx'), models.Index(fields=['incident_date'], name='behavior_co_inciden_a8055f_idx')],
            },
        ),
        migrations.CreateModel(
            name='BehaviorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pendiente de sincronizar'), ('PROCESSING', 'En procesamiento'), ('SYNCED', 'Sincronizado'), ('ERROR', 'Error de sincronización'), ('CONFLICT', 'Conflicto detectado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de Sincronización')),
                ('sync_version', models.PositiveIntegerField(default=1, verbose_name='Versión de Sincronización')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado en')),
                ('device_origin', models.CharField(blank=True, max_length=40, null=True, verbose_name='Dispositivo de Origen')),
                ('conflict_resolved', models.BooleanField(default=False, verbose_name='Conflicto Resuelto')),
                ('conflict_notes', models.TextField(blank=True, null=True, verbose_name='Notas de Conflicto')),
                ('general_observation', models.TextField(blank=True, null=True, verbose_name='Observación general')),
                ('override_reason', models.TextField(blank=True, null=True, verbose_name='Razón de anulación')),
                ('evaluation_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de evaluación')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_behavior_evaluations', to='academic.academicperiod', verbose_name='Período Académico')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_evaluations_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('calculated_scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_calculated_evaluations', to='grading.qualitativescale', verbose_name='Escala Calculada')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_evaluations_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_behavior_evaluations', to='students.enrollment', verbose_name='Matrícula')),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Evaluado por')),
                ('final_scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_final_evaluations', to='grading.qualitativescale', verbose_name='Escala Final')),
            ],
            options={
                'verbose_name': 'Evaluación de Conducta',
                'verbose_name_plural': 'Evaluaciones de Conducta',
                'indexes': [models.Index(fields=['academic_period', 'calculated_scale'], name='behavior_be_academi_05b2f9_idx'), models.Index(fields=['evaluated_by', 'evaluation_date'], name='behavior_be_evaluat_394152_idx')],
                'unique_together': {('enrollment', 'academic_period')},
            },
        ),
    ]
