# Generated by Django 4.2.30 on 2026-06-16 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('behavior', '0001_initial'),
        ('grading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductincident',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_incidents', to='students.enrollment', verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='conductincident',
            name='incident_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='behavior.incidenttype', verbose_name='Tipo de incidente'),
        ),
        migrations.AddField(
            model_name='conductincident',
            name='severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='behavior.severity', verbose_name='Severidad'),
        ),
        migrations.AddField(
            model_name='behaviorevaluation',
            name='academic_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_evaluations', to='academic.academicperiod', verbose_name='Período Académico'),
        ),
        migrations.AddField(
            model_name='behaviorevaluation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_evaluations_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='behaviorevaluation',
            name='calculated_scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculated_evaluations', to='grading.qualitativescale', verbose_name='Escala Calculada'),
        ),
        migrations.AddField(
            model_name='behaviorevaluation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_evaluations_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='behaviorevaluation',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_evaluations', to='students.enrollment', verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='behaviorevaluation',
            name='evaluated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Evaluado por'),
        ),
        migrations.AddField(
            model_name='behaviorevaluation',
            name='final_scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_evaluations', to='grading.qualitativescale', verbose_name='Escala Final'),
        ),
        migrations.AddIndex(
            model_name='conductincident',
            index=models.Index(fields=['enrollment', 'academic_period'], name='behavior_co_enrollm_beb9d1_idx'),
        ),
        migrations.AddIndex(
            model_name='conductincident',
            index=models.Index(fields=['academic_period', 'severity'], name='behavior_co_academi_328217_idx'),
        ),
        migrations.AddIndex(
            model_name='conductincident',
            index=models.Index(fields=['incident_date'], name='behavior_co_inciden_a8055f_idx'),
        ),
        migrations.AddIndex(
            model_name='behaviorevaluation',
            index=models.Index(fields=['academic_period', 'calculated_scale'], name='behavior_be_academi_05b2f9_idx'),
        ),
        migrations.AddIndex(
            model_name='behaviorevaluation',
            index=models.Index(fields=['evaluated_by', 'evaluation_date'], name='behavior_be_evaluat_394152_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='behaviorevaluation',
            unique_together={('enrollment', 'academic_period')},
        ),
    ]
