# Generated by Django 4.2.30 on 2026-06-04 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre del Período')),
                ('period_type', models.CharField(choices=[('REGULAR', 'Regular'), ('SUPLETORIO', 'Supletorio'), ('REFUERZO', 'Refuerzo')], default='REGULAR', max_length=20, verbose_name='Tipo de período')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('is_regular_period', models.BooleanField(default=True, verbose_name='Período Regular')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school_year', verbose_name='Año Escolar')),
            ],
            options={
                'verbose_name': 'Período Académico',
                'verbose_name_plural': 'Períodos Académicos',
            },
        ),
        migrations.CreateModel(
            name='InterdisciplinaryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('delivery_date', models.DateField(verbose_name='Fecha de entrega')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interdisciplinary_projects', to='academic.academic_period', verbose_name='Período Académico')),
            ],
            options={
                'verbose_name': 'Proyecto Interdisciplinario',
                'verbose_name_plural': 'Proyectos Interdisciplinarios',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Materia')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='SubjectAcademicConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_hours', models.IntegerField(verbose_name='Horas Semanales')),
                ('pedagogical_order', models.IntegerField(verbose_name='Orden Pedagógico')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obligatoria')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('academic_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.academicgrade', verbose_name='Grado Académico')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Configuración de Materia por Grado',
                'verbose_name_plural': 'Configuraciones de Materia por Grado',
                'ordering': ['pedagogical_order'],
            },
        ),
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.school_year', verbose_name='Año Escolar')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.section', verbose_name='Sección')),
                ('subject_academic_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subjectacademicconfig', verbose_name='Configuración de Materia')),
            ],
            options={
                'verbose_name': 'Oferta de Materia',
                'verbose_name_plural': 'Ofertas de Materias',
                'unique_together': {('school_year', 'section', 'subject_academic_config')},
            },
        ),
        migrations.CreateModel(
            name='Teacher_Subject_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subjectoffering', verbose_name='Oferta de Materia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Docente-Materia-Sección',
                'verbose_name_plural': 'Docentes-Materias-Secciones',
            },
        ),
        migrations.CreateModel(
            name='SubjectProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interdisciplinary_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_projects', to='academic.interdisciplinaryproject', verbose_name='Proyecto Interdisciplinario')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_projects', to='academic.subjectoffering', verbose_name='Oferta de Asignatura')),
            ],
            options={
                'verbose_name': 'Asignatura del Proyecto',
                'verbose_name_plural': 'Asignaturas del Proyecto',
                'unique_together': {('interdisciplinary_project', 'subject_offering')},
            },
        ),
    ]
