# Generated by Django 4.2.30 on 2026-06-09 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre del Período')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('is_regular_period', models.BooleanField(default=True, verbose_name='Período Regular')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('parent_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_periods', to='academic.academicperiod', verbose_name='Período Padre')),
            ],
            options={
                'verbose_name': 'Período Académico',
                'verbose_name_plural': 'Períodos Académicos',
            },
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.IntegerField(unique=True, verbose_name='Código (1-7)')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre del día')),
            ],
            options={
                'verbose_name': 'Día de la Semana',
                'verbose_name_plural': 'Días de la Semana',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InterdisciplinaryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('delivery_date', models.DateField(verbose_name='Fecha de entrega')),
                ('product_max_score', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Puntaje máximo del producto')),
                ('presentation_max_score', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Puntaje máximo de la presentación')),
                ('product_rubric', models.TextField(blank=True, null=True, verbose_name='Rúbrica del producto')),
                ('presentation_rubric', models.TextField(blank=True, null=True, verbose_name='Rúbrica de la presentación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interdisciplinary_projects', to='academic.academicperiod', verbose_name='Período Académico')),
            ],
            options={
                'verbose_name': 'Proyecto Interdisciplinario',
                'verbose_name_plural': 'Proyectos Interdisciplinarios',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PeriodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Período',
                'verbose_name_plural': 'Tipos de Período',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Materia')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='SubjectAcademicConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('weekly_hours', models.IntegerField(verbose_name='Horas Semanales')),
                ('pedagogical_order', models.IntegerField(verbose_name='Orden Pedagógico')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obligatoria')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('academic_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.academicgrade', verbose_name='Grado Académico')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Configuración de Materia por Grado',
                'verbose_name_plural': 'Configuraciones de Materia por Grado',
                'ordering': ['pedagogical_order'],
            },
        ),
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.schoolyear', verbose_name='Año Escolar')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.section', verbose_name='Sección')),
                ('subject_academic_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subjectacademicconfig', verbose_name='Configuración de Materia')),
            ],
            options={
                'verbose_name': 'Oferta de Materia',
                'verbose_name_plural': 'Ofertas de Materias',
            },
        ),
        migrations.CreateModel(
            name='SubjectProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('interdisciplinary_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_projects', to='academic.interdisciplinaryproject', verbose_name='Proyecto Interdisciplinario')),
                ('responsible_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Docente responsable')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_projects', to='academic.subjectoffering', verbose_name='Oferta de Asignatura')),
            ],
            options={
                'verbose_name': 'Asignatura del Proyecto',
                'verbose_name_plural': 'Asignaturas del Proyecto',
                'unique_together': {('interdisciplinary_project', 'subject_offering')},
            },
        ),
        migrations.AddField(
            model_name='interdisciplinaryproject',
            name='subject_offerings',
            field=models.ManyToManyField(through='academic.SubjectProject', to='academic.subjectoffering', verbose_name='Ofertas de Materia'),
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('classroom', models.CharField(blank=True, max_length=50, verbose_name='Aula')),
                ('building', models.CharField(blank=True, max_length=50, verbose_name='Edificio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('day_of_week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.dayofweek', verbose_name='Día de la Semana')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academic.subjectoffering', verbose_name='Oferta de Materia')),
            ],
            options={
                'verbose_name': 'Horario Académico',
                'verbose_name_plural': 'Horarios Académicos',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='period_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.periodtype', verbose_name='Tipo de período'),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.schoolyear', verbose_name='Año Escolar'),
        ),
        migrations.CreateModel(
            name='TeacherSubjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subjectoffering', verbose_name='Oferta de Materia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Docente-Materia-Sección',
                'verbose_name_plural': 'Docentes-Materias-Secciones',
                'indexes': [models.Index(fields=['user', 'is_active'], name='academic_te_user_id_6a0f7f_idx')],
                'unique_together': {('user', 'subject_offering')},
            },
        ),
        migrations.AddIndex(
            model_name='subjectoffering',
            index=models.Index(fields=['section', 'school_year'], name='academic_su_section_299663_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectoffering',
            unique_together={('school_year', 'section', 'subject_academic_config')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectacademicconfig',
            unique_together={('subject', 'academic_grade')},
        ),
        migrations.AlterUniqueTogether(
            name='classschedule',
            unique_together={('subject_offering', 'day_of_week', 'start_time')},
        ),
    ]
