# Generated by Django 4.2.30 on 2026-06-10 01:20

import apps.academic.models.academic_period
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicperiod',
            name='period_type',
            field=models.ForeignKey(default=apps.academic.models.academic_period._get_default_period_type, on_delete=django.db.models.deletion.PROTECT, to='academic.periodtype', verbose_name='Tipo de período'),
        ),
    ]
