# Generated by Django 4.2.30 on 2026-06-16 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodtype',
            name='divisions_per_year',
            field=models.PositiveSmallIntegerField(default=1, help_text='Cantidad de veces que el año escolar se divide con este tipo de período (ej: 3 para Trimestre, 2 para Semestre, 4 para Bimestre).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Divisiones por año'),
        ),
    ]
