# Generated by Django 6.0.4 on 2026-04-30 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_start_time', models.TimeField(help_text='Hora de inicio de la jornada escolar')),
                ('class_duration_minutes', models.IntegerField(help_text='Duración en minutos de cada clase')),
                ('break_duration_minutes', models.IntegerField(help_text='Duración en minutos del recreo')),
                ('slots_before_break', models.IntegerField(help_text='Número de periodos antes del primer recreo')),
                ('total_slots_per_day', models.IntegerField(help_text='Total de periodos de clase por día')),
                ('timing_regime', models.OneToOneField(help_text='Régimen horario al que aplica esta configuración', on_delete=django.db.models.deletion.CASCADE, to='academic.timing_regime')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_consecutive_slots', models.IntegerField(default=1, help_text='Número de periodos seguidos requeridos')),
                ('max_slots_per_day', models.IntegerField(default=2, help_text='Máximo de periodos permitidos por día')),
                ('preferred_room_type', models.CharField(blank=True, help_text='Preferencia de tipo de aula', max_length=50, null=True)),
                ('subject', models.ForeignKey(help_text='Materia restringida', on_delete=django.db.models.deletion.CASCADE, to='academic.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la hora/periodo', max_length=50)),
                ('day_of_week', models.IntegerField(help_text='Día de la semana (1-7)')),
                ('start_time', models.TimeField(help_text='Hora de inicio del periodo')),
                ('end_time', models.TimeField(help_text='Hora de fin del periodo')),
                ('is_break', models.BooleanField(default=False, help_text='Indica si es tiempo de descanso')),
                ('timing_regime', models.ForeignKey(help_text='Régimen horario que contiene este slot', on_delete=django.db.models.deletion.CASCADE, to='academic.timing_regime')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, help_text='Indica disponibilidad del docente')),
                ('school_year', models.ForeignKey(help_text='Año escolar', on_delete=django.db.models.deletion.CASCADE, to='institutions.school_year')),
                ('user', models.ForeignKey(help_text='Docente', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.ForeignKey(help_text='Franja horaria', on_delete=django.db.models.deletion.CASCADE, to='scheduling.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manual', models.BooleanField(default=True, help_text='Indica si fue asignado manualmente')),
                ('active', models.BooleanField(default=True, help_text='Indica si el slot está activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(help_text='Aula asignada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.classroom')),
                ('school_year', models.ForeignKey(help_text='Año escolar', on_delete=django.db.models.deletion.CASCADE, to='institutions.school_year')),
                ('teacher_subject_section', models.ForeignKey(help_text='Asignación académica', on_delete=django.db.models.deletion.CASCADE, to='academic.teacher_subject_section')),
                ('time_slot', models.ForeignKey(help_text='Franja horaria ocupada', on_delete=django.db.models.deletion.CASCADE, to='scheduling.timeslot')),
            ],
            options={
                'unique_together': {('teacher_subject_section', 'time_slot')},
            },
        ),
    ]
