# Generated by Django 4.2.30 on 2026-05-10 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la hora/periodo', max_length=50, verbose_name='Nombre')),
                ('day_of_week', models.IntegerField(help_text='Día de la semana (1-7)', verbose_name='Día de la Semana')),
                ('start_time', models.TimeField(help_text='Hora de inicio del periodo', verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(help_text='Hora de fin del periodo', verbose_name='Hora de Fin')),
                ('is_break', models.BooleanField(default=False, help_text='Indica si es tiempo de descanso', verbose_name='Es Recreo')),
                ('timing_regime', models.ForeignKey(help_text='Régimen horario que contiene este slot', on_delete=django.db.models.deletion.CASCADE, to='academic.timing_regime', verbose_name='Régimen de Horario')),
            ],
            options={
                'verbose_name': 'Franja Horaria',
                'verbose_name_plural': 'Franjas Horarias',
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='Está Disponible')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.timeslot', verbose_name='Franja Horaria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Disponibilidad del Docente',
                'verbose_name_plural': 'Disponibilidades de los Docentes',
            },
        ),
        migrations.CreateModel(
            name='SubjectConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_consecutive_slots', models.IntegerField(default=1, help_text='Número de periodos seguidos requeridos', verbose_name='Periodos Consecutivos Requeridos')),
                ('max_slots_per_day', models.IntegerField(default=2, help_text='Máximo de periodos permitidos por día', verbose_name='Máximo de Periodos por Día')),
                ('preferred_room_type', models.ForeignKey(blank=True, help_text='Preferencia de tipo de aula', null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.roomtype', verbose_name='Tipo de Aula Preferida')),
                ('subject_academic_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.subjectacademicconfig', verbose_name='Configuración de Materia')),
            ],
            options={
                'verbose_name': 'Restricción de Materia',
                'verbose_name_plural': 'Restricciones de Materias',
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_start_time', models.TimeField(help_text='Hora de inicio de la jornada escolar', verbose_name='Hora de Inicio del Día')),
                ('class_duration_minutes', models.IntegerField(help_text='Duración en minutos de cada clase', verbose_name='Duración de Clase (min)')),
                ('break_duration_minutes', models.IntegerField(help_text='Duración en minutos del recreo', verbose_name='Duración del Recreo (min)')),
                ('slots_before_break', models.IntegerField(help_text='Número de periodos antes del primer recreo', verbose_name='Periodos antes del Recreo')),
                ('total_slots_per_day', models.IntegerField(help_text='Total de periodos de clase por día', verbose_name='Total de Periodos por Día')),
                ('timing_regime', models.OneToOneField(help_text='Régimen horario al que aplica esta configuración', on_delete=django.db.models.deletion.CASCADE, to='academic.timing_regime', verbose_name='Régimen de Horario')),
            ],
            options={
                'verbose_name': 'Configuración de Plantilla de Horario',
                'verbose_name_plural': 'Configuraciones de Plantilla de Horarios',
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manual', models.BooleanField(default=True, help_text='Indica si fue asignado manualmente', verbose_name='Asignación Manual')),
                ('active', models.BooleanField(default=True, help_text='Indica si el slot está activo', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('classroom', models.ForeignKey(help_text='Aula asignada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.classroom', verbose_name='Aula')),
                ('teacher_subject_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.teacher_subject_section', verbose_name='Asignación Académica')),
                ('time_slot', models.ForeignKey(help_text='Franja horaria ocupada', on_delete=django.db.models.deletion.CASCADE, to='scheduling.timeslot', verbose_name='Franja Horaria')),
            ],
            options={
                'verbose_name': 'Bloque de Horario',
                'verbose_name_plural': 'Bloques de Horario',
                'unique_together': {('teacher_subject_section', 'time_slot')},
            },
        ),
    ]
