# Generated by Django 4.2.30 on 2026-06-26 19:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('academic_teacher_subject', '0001_initial'),
        ('attendance_attendance_status', '0001_initial'),
        ('academic_period', '0001_initial'),
        ('academic_class_schedule', '0001_initial'),
        ('attendance_absence_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pendiente de sincronizar'), ('PROCESSING', 'En procesamiento'), ('SYNCED', 'Sincronizado'), ('ERROR', 'Error de sincronización'), ('CONFLICT', 'Conflicto detectado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de Sincronización')),
                ('sync_version', models.PositiveIntegerField(default=1, verbose_name='Versión de Sincronización')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado en')),
                ('device_origin', models.CharField(blank=True, max_length=40, null=True, verbose_name='Dispositivo de Origen')),
                ('conflict_resolved', models.BooleanField(default=False, verbose_name='Conflicto Resuelto')),
                ('conflict_notes', models.TextField(blank=True, default='', verbose_name='Notas de Conflicto')),
                ('attendance_date', models.DateField(verbose_name='Fecha')),
                ('observation', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('absence_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance_absence_type.absencetype', verbose_name='Tipo de ausencia')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academic_period.academicperiod', verbose_name='Periodo Academico')),
                ('attendance_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance_attendance_status.attendancestatus', verbose_name='Estado')),
                ('class_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_class_schedule.classschedule', verbose_name='Horario de clase')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.enrollment', verbose_name='Matricula')),
                ('teacher_subject_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academic_teacher_subject.teachersubjectsection', verbose_name='Clase')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'indexes': [models.Index(fields=['enrollment', 'academic_period'], name='attendance__enrollm_e5a187_idx'), models.Index(fields=['teacher_subject_section', 'attendance_date'], name='attendance__teacher_b6cbd6_idx'), models.Index(fields=['attendance_date', 'academic_period'], name='attendance__attenda_92da66_idx'), models.Index(fields=['class_schedule', 'attendance_date'], name='attendance__class_s_01bdf4_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('class_schedule__isnull', True)), fields=('enrollment', 'teacher_subject_section', 'attendance_date'), name='unique_attendance_no_schedule'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('class_schedule__isnull', False)), fields=('enrollment', 'class_schedule', 'attendance_date'), name='unique_attendance_with_schedule'),
        ),
    ]
