# Generated by Django 4.2.30 on 2026-06-24 02:31

import apps.academic.academic_period.infrastructure.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_period_type', '0001_initial'),
        ('institutions_school_year', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre del Período')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('year_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de contribución de este período a la nota anual (ej: 40.00 para Q1)', max_digits=5, null=True, verbose_name='Peso en el año (%)')),
                ('is_regular_period', models.BooleanField(default=True, verbose_name='Período Regular')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('period_type', models.ForeignKey(default=apps.academic.academic_period.infrastructure.models._get_default_period_type, on_delete=django.db.models.deletion.PROTECT, to='academic_period_type.periodtype', verbose_name='Tipo de período')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_periods', to='institutions_school_year.schoolyear', verbose_name='Año Escolar')),
            ],
            options={
                'verbose_name': 'Período Académico',
                'verbose_name_plural': 'Períodos Académicos',
            },
        ),
    ]
