# Generated by Django 4.2.30 on 2026-07-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_period', '0002_academicperiod_grades_locked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicperiod',
            options={'ordering': ['start_date'], 'verbose_name': 'Período Académico', 'verbose_name_plural': 'Períodos Académicos'},
        ),
    ]
