# Generated by Django 4.2.30 on 2026-06-09 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Ausencia',
                'verbose_name_plural': 'Tipos de Ausencia',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo', models.CharField(blank=True, choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=10, null=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Estado de Asistencia',
                'verbose_name_plural': 'Estados de Asistencia',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pendiente de sincronizar'), ('PROCESSING', 'En procesamiento'), ('SYNCED', 'Sincronizado'), ('ERROR', 'Error de sincronización'), ('CONFLICT', 'Conflicto detectado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de Sincronización')),
                ('sync_version', models.PositiveIntegerField(default=1, verbose_name='Versión de Sincronización')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado en')),
                ('device_origin', models.CharField(blank=True, max_length=40, null=True, verbose_name='Dispositivo de Origen')),
                ('conflict_resolved', models.BooleanField(default=False, verbose_name='Conflicto Resuelto')),
                ('conflict_notes', models.TextField(blank=True, null=True, verbose_name='Notas de Conflicto')),
                ('attendance_date', models.DateField(null=True, verbose_name='Fecha')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('absence_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.absencetype', verbose_name='Tipo de ausencia')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academic.academicperiod', verbose_name='Período Académico')),
                ('attendance_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='attendance.attendancestatus', verbose_name='Estado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('enrollment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.enrollment', verbose_name='Matrícula')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('teacher_subject_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academic.teachersubjectsection', verbose_name='Clase')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'indexes': [models.Index(fields=['enrollment', 'academic_period'], name='attendance__enrollm_422d6e_idx'), models.Index(fields=['teacher_subject_section', 'attendance_date'], name='attendance__teacher_dffb1b_idx'), models.Index(fields=['attendance_date', 'academic_period'], name='attendance__attenda_db700d_idx')],
                'unique_together': {('enrollment', 'teacher_subject_section', 'attendance_date')},
            },
        ),
    ]
