# Generated by Django 4.2.30 on 2026-06-10 01:14

from django.db import migrations, models
import django.db.models.deletion


def set_null_enrollments(apps, schema_editor):
    Attendance = apps.get_model("attendance", "Attendance")
    Attendance.objects.filter(enrollment__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(set_null_enrollments, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="attendance",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="students.enrollment",
                verbose_name="Matrícula",
            ),
        ),
    ]
