# Generated by Django 4.2.30 on 2026-06-16 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('academic', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.enrollment', verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher_subject_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academic.teachersubjectsection', verbose_name='Clase'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['enrollment', 'academic_period'], name='attendance__enrollm_422d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['teacher_subject_section', 'attendance_date'], name='attendance__teacher_dffb1b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['attendance_date', 'academic_period'], name='attendance__attenda_db700d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('enrollment', 'teacher_subject_section', 'attendance_date')},
        ),
    ]
