# Generated by Django 4.2.30 on 2026-06-21 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_periodtype_divisions_per_year'),
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.classschedule', verbose_name='Horario de clase'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['class_schedule', 'attendance_date'], name='attendance__class_s_747beb_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('class_schedule__isnull', True)), fields=('enrollment', 'teacher_subject_section', 'attendance_date'), name='unique_attendance_no_schedule'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('class_schedule__isnull', False)), fields=('enrollment', 'class_schedule', 'attendance_date'), name='unique_attendance_with_schedule'),
        ),
    ]
