# Generated by Django 4.2.30 on 2026-06-26 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions_school_year', '0001_initial'),
        ('institutions_academic_grade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Codigo')),
                ('parallel', models.CharField(max_length=255, verbose_name='Paralelo')),
                ('capacity', models.IntegerField(verbose_name='Capacidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('academic_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions_academic_grade.academicgrade', verbose_name='Grado Academico')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions_school_year.schoolyear', verbose_name='Año Escolar')),
            ],
            options={
                'verbose_name': 'Seccion',
                'verbose_name_plural': 'Secciones',
                'unique_together': {('school_year', 'academic_grade', 'parallel')},
            },
        ),
    ]
