# Generated by Django 6.0.4 on 2026-04-30 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_rate', models.DecimalField(decimal_places=2, help_text='Porcentaje de asistencia', max_digits=5)),
                ('consecutive_absences_max', models.IntegerField(help_text='Máximo de faltas seguidas')),
                ('tardiness_count', models.IntegerField(help_text='Total de atrasos')),
                ('avg_grade_normalized', models.DecimalField(decimal_places=2, help_text='Promedio general normalizado', max_digits=5)),
                ('grade_trend_slope', models.DecimalField(decimal_places=2, help_text='Tendencia de rendimiento', max_digits=5)),
                ('failing_subjects_count', models.IntegerField(help_text='Materias con pérdida')),
                ('conduct_score', models.DecimalField(decimal_places=2, help_text='Puntaje de comportamiento', max_digits=5)),
                ('family_notified_ratio', models.DecimalField(decimal_places=2, help_text='Ratio de notificación familiar', max_digits=5)),
                ('prev_period_avg_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Promedio periodo anterior', max_digits=5, null=True)),
                ('age_grade_gap', models.IntegerField(help_text='Desfase edad-grado')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('academic_period', models.ForeignKey(help_text='Período académico', on_delete=django.db.models.deletion.CASCADE, to='academic.academic_period')),
                ('student', models.ForeignKey(help_text='Estudiante', on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.DecimalField(decimal_places=2, help_text='Puntaje de riesgo calculado', max_digits=5)),
                ('risk_label', models.CharField(help_text='Etiqueta de nivel de riesgo (Bajo, Medio, Alto)', max_length=20)),
                ('top_factors', models.JSONField(help_text='Factores principales que contribuyen al riesgo')),
                ('model_version', models.CharField(help_text='Versión del modelo de IA/Analítica', max_length=50)),
                ('calculated_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de cálculo del puntaje')),
                ('academic_period', models.ForeignKey(help_text='Período académico correspondiente', on_delete=django.db.models.deletion.CASCADE, to='academic.academic_period')),
                ('student', models.ForeignKey(help_text='Estudiante evaluado', on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
    ]
