# Generated by Django 4.2.30 on 2026-05-10 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Factor de Riesgo',
                'verbose_name_plural': 'Factores de Riesgo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentRiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puntaje de Riesgo')),
                ('risk_label', models.CharField(max_length=20, verbose_name='Etiqueta de Riesgo')),
                ('model_version', models.CharField(max_length=50, verbose_name='Versión del Modelo')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cálculo')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academic_period', verbose_name='Período Académico')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Puntaje de Riesgo del Estudiante',
                'verbose_name_plural': 'Puntajes de Riesgo de los Estudiantes',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_rate', models.DecimalField(decimal_places=2, help_text='Porcentaje de asistencia', max_digits=5, verbose_name='Tasa de Asistencia')),
                ('consecutive_absences_max', models.IntegerField(help_text='Máximo de faltas seguidas', verbose_name='Máximo de Faltas Consecutivas')),
                ('tardiness_count', models.IntegerField(help_text='Total de atrasos', verbose_name='Contador de Atrasos')),
                ('avg_grade_normalized', models.DecimalField(decimal_places=2, help_text='Promedio general normalizado', max_digits=5, verbose_name='Promedio Normalizado')),
                ('grade_trend_slope', models.DecimalField(decimal_places=2, help_text='Tendencia de rendimiento', max_digits=5, verbose_name='Tendencia de Notas')),
                ('failing_subjects_count', models.IntegerField(help_text='Materias con pérdida', verbose_name='Materias Reprobadas')),
                ('conduct_score', models.DecimalField(decimal_places=2, help_text='Puntaje de comportamiento', max_digits=5, verbose_name='Puntaje de Conducta')),
                ('family_notified_ratio', models.DecimalField(decimal_places=2, help_text='Ratio de notificación familiar', max_digits=5, verbose_name='Ratio de Notificación Familiar')),
                ('prev_period_avg_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Promedio periodo anterior', max_digits=5, null=True, verbose_name='Promedio Período Anterior')),
                ('age_grade_gap', models.IntegerField(help_text='Desfase edad-grado', verbose_name='Brecha Edad-Grado')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cálculo')),
                ('academic_period', models.ForeignKey(help_text='Período académico', on_delete=django.db.models.deletion.CASCADE, to='academic.academic_period', verbose_name='Período Académico')),
                ('student', models.ForeignKey(help_text='Estudiante', on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Instantánea de Métricas de Estudiante',
                'verbose_name_plural': 'Instantáneas de Métricas de Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='StudentRiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso de Contribución (%)')),
                ('risk_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.riskfactor', verbose_name='Factor de Riesgo')),
                ('student_risk_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='analytics.studentriskscore', verbose_name='Puntaje de Riesgo')),
            ],
            options={
                'verbose_name': 'Factor de Riesgo del Estudiante',
                'verbose_name_plural': 'Factores de Riesgo de los Estudiantes',
                'unique_together': {('student_risk_score', 'risk_factor')},
            },
        ),
    ]
