# Generated by Django 4.2.30 on 2026-06-04 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Factor de Riesgo',
                'verbose_name_plural': 'Factores de Riesgo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentRiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Puntaje de Riesgo')),
                ('risk_label', models.CharField(default='', max_length=20, verbose_name='Etiqueta de Riesgo')),
                ('model_version', models.CharField(default='', max_length=50, verbose_name='Versión del Modelo')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cálculo')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academic_period', verbose_name='Período Académico')),
                ('enrollment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.enrollment', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Puntaje de Riesgo del Estudiante',
                'verbose_name_plural': 'Puntajes de Riesgo de los Estudiantes',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa de Asistencia')),
                ('consecutive_absences_max', models.IntegerField(default=0, verbose_name='Máximo de Faltas Consecutivas')),
                ('tardiness_count', models.IntegerField(default=0, verbose_name='Contador de Atrasos')),
                ('justified_absences', models.IntegerField(default=0, verbose_name='Ausencias Justificadas')),
                ('unjustified_absences', models.IntegerField(default=0, verbose_name='Ausencias Injustificadas')),
                ('formative_avg_normalized', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Promedio Formativo Normalizado')),
                ('summative_avg_normalized', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Promedio Sumativo Normalizado')),
                ('grade_trend_slope', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tendencia de Notas')),
                ('failing_subjects_count', models.IntegerField(default=0, verbose_name='Materias Reprobadas')),
                ('conduct_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Puntaje de Conducta')),
                ('severe_incidents_count', models.IntegerField(default=0, verbose_name='Incidentes Graves')),
                ('family_notified_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ratio de Notificación Familiar')),
                ('prev_period_avg_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Promedio Período Anterior')),
                ('age_grade_gap', models.IntegerField(default=0, verbose_name='Brecha Edad-Grado')),
                ('is_repeat', models.BooleanField(default=False, verbose_name='Es Repitente')),
                ('has_special_needs', models.BooleanField(default=False, verbose_name='Tiene NEE')),
                ('residential_zone', models.CharField(blank=True, max_length=50, verbose_name='Zona de Residencia')),
                ('distance_to_school_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Distancia al Colegio (km)')),
                ('active_alerts', models.IntegerField(default=0, verbose_name='Alertas Activas')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cálculo')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academic_period', verbose_name='Período Académico')),
                ('enrollment', models.ForeignKey(help_text='Matrícula del estudiante', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.enrollment', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Instantánea de Métricas de Estudiante',
                'verbose_name_plural': 'Instantáneas de Métricas de Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='StudentRiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso de Contribución (%)')),
                ('risk_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.riskfactor', verbose_name='Factor de Riesgo')),
                ('student_risk_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='analytics.studentriskscore', verbose_name='Puntaje de Riesgo')),
            ],
            options={
                'verbose_name': 'Factor de Riesgo del Estudiante',
                'verbose_name_plural': 'Factores de Riesgo de los Estudiantes',
                'unique_together': {('student_risk_score', 'risk_factor')},
            },
        ),
        migrations.CreateModel(
            name='EarlyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_attendance', 'Baja Asistencia'), ('failing_grades', 'Calificaciones Bajas'), ('behavioral', 'Problemas de Conducta'), ('dropout_risk', 'Riesgo de Deserción'), ('socioemotional', 'Problemas Socioemocionales')], max_length=50, verbose_name='Tipo de alerta')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('urgency_level', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=20, verbose_name='Nivel de urgencia')),
                ('attended', models.BooleanField(default=False, verbose_name='Atendida')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de detección')),
                ('attended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de atención')),
                ('response_actions', models.TextField(blank=True, null=True, verbose_name='Acciones de respuesta')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_alerts', to='academic.academic_period', verbose_name='Período Académico')),
                ('attended_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Atendida por')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_alerts', to='students.enrollment', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Alerta Temprana',
                'verbose_name_plural': 'Alertas Tempranas',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['attended', 'urgency_level'], name='analytics_e_attende_b372a7_idx'), models.Index(fields=['enrollment', 'academic_period'], name='analytics_e_enrollm_64cad3_idx')],
            },
        ),
    ]
