# Generated by Django 4.2.30 on 2026-06-16 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentriskscore',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.enrollment', verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='studentriskfactor',
            name='risk_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.riskfactor', verbose_name='Factor de Riesgo'),
        ),
        migrations.AddField(
            model_name='studentriskfactor',
            name='student_risk_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='analytics.studentriskscore', verbose_name='Puntaje de Riesgo'),
        ),
        migrations.AddField(
            model_name='studentfeaturesnapshot',
            name='academic_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicperiod', verbose_name='Período Académico'),
        ),
        migrations.AddField(
            model_name='studentfeaturesnapshot',
            name='enrollment',
            field=models.ForeignKey(help_text='Matrícula del estudiante', on_delete=django.db.models.deletion.CASCADE, to='students.enrollment', verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='earlyalert',
            name='academic_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_alerts', to='academic.academicperiod', verbose_name='Período Académico'),
        ),
        migrations.AddField(
            model_name='earlyalert',
            name='attended_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Atendida por'),
        ),
        migrations.AddField(
            model_name='earlyalert',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_alerts', to='students.enrollment', verbose_name='Matrícula'),
        ),
        migrations.AddIndex(
            model_name='studentriskscore',
            index=models.Index(fields=['academic_period', 'risk_label'], name='analytics_s_academi_5ce839_idx'),
        ),
        migrations.AddIndex(
            model_name='studentriskscore',
            index=models.Index(fields=['calculated_at'], name='analytics_s_calcula_1b1403_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentriskscore',
            constraint=models.UniqueConstraint(fields=('enrollment', 'academic_period', 'model_version'), name='unique_enrollment_period_model_version'),
        ),
        migrations.AddConstraint(
            model_name='studentriskfactor',
            constraint=models.UniqueConstraint(fields=('student_risk_score', 'risk_factor'), name='unique_student_risk_factor'),
        ),
        migrations.AddIndex(
            model_name='studentfeaturesnapshot',
            index=models.Index(fields=['academic_period', 'failing_subjects_count'], name='analytics_s_academi_6f0d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeaturesnapshot',
            index=models.Index(fields=['academic_period', 'attendance_rate'], name='analytics_s_academi_4d0581_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeaturesnapshot',
            index=models.Index(fields=['calculated_at'], name='analytics_s_calcula_e5ec06_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeaturesnapshot',
            index=models.Index(fields=['enrollment', 'academic_period', 'is_current'], name='analytics_s_enrollm_a88078_idx'),
        ),
        migrations.AddIndex(
            model_name='earlyalert',
            index=models.Index(fields=['attended', 'urgency_level'], name='analytics_e_attende_b372a7_idx'),
        ),
        migrations.AddIndex(
            model_name='earlyalert',
            index=models.Index(fields=['enrollment', 'academic_period'], name='analytics_e_enrollm_64cad3_idx'),
        ),
    ]
