# Generated by Django 4.2.30 on 2026-06-09 06:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('institutions', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Actualización')),
                ('metric_type', models.CharField(max_length=50, verbose_name='Tipo de Métrica')),
                ('metric_value', models.JSONField(default=dict, verbose_name='Valor de la Métrica')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Calculado en')),
                ('academic_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.academicgrade', verbose_name='Grado Académico')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicperiod', verbose_name='Período Académico')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.section', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Métrica de Dashboard',
                'verbose_name_plural': 'Métricas de Dashboard',
                'indexes': [models.Index(fields=['academic_period', 'metric_type'], name='analytics_d_academi_b2b6fa_idx'), models.Index(fields=['calculated_at'], name='analytics_d_calcula_0998f3_idx')],
                'unique_together': {('academic_period', 'section', 'metric_type')},
            },
        ),
    ]
