# Generated by Django 4.2.30 on 2026-06-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_dashboardmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmetric',
            name='metric_schema_version',
            field=models.CharField(blank=True, default='1.0', max_length=10, verbose_name='Versión del Esquema'),
        ),
        migrations.AddField(
            model_name='studentfeaturesnapshot',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Es actual'),
        ),
        migrations.AddField(
            model_name='studentfeaturesnapshot',
            name='snapshot_trigger',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Automático'), ('BATCH', 'Por Lote')], default='MANUAL', max_length=10, verbose_name='Desencadenante'),
        ),
    ]
