# Generated by Django 4.2.30 on 2026-06-21 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_add_unique_enrollment_period'),
        ('academic', '0002_periodtype_divisions_per_year'),
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentfeaturesnapshot',
            unique_together={('enrollment', 'academic_period')},
        ),
    ]
