# Generated by Django 4.2.30 on 2026-06-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_add_unique_enrollment_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfeaturesnapshot',
            name='active_alerts',
        ),
    ]
