# Generated by Django 4.2.30 on 2026-06-23 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_add_unique_enrollment_period'),
        ('people', '0001_initial'),
        ('analytics', '0004_remove_studentfeaturesnapshot_active_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeaturesnapshot',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_snapshots', to='people.city', verbose_name='Ciudad de Origen'),
        ),
        migrations.AddField(
            model_name='studentfeaturesnapshot',
            name='special_needs_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_snapshots', to='students.specialneedstype', verbose_name='Tipo de NEE'),
        ),
        migrations.AddField(
            model_name='studentfeaturesnapshot',
            name='withdrawal_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_snapshots', to='students.withdrawalreason', verbose_name='Motivo de Retiro'),
        ),
    ]
