# Generated by Django 4.2.30 on 2026-06-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_studentfeaturesnapshot_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('engine', models.CharField(choices=[('reglas', 'Motor de reglas (ponderado + umbrales)'), ('ML', 'Modelo de Machine Learning')], default='reglas', max_length=10, verbose_name='Motor de cálculo')),
                ('preset', models.CharField(choices=[('conservador', 'Conservador'), ('equilibrado', 'Equilibrado'), ('estricto', 'Estricto'), ('personalizado', 'Personalizado')], default='equilibrado', max_length=15, verbose_name='Preset aplicado')),
                ('weight_conducta', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='Peso Conducta (%)')),
                ('weight_asistencia', models.DecimalField(decimal_places=2, default=35.0, max_digits=5, verbose_name='Peso Asistencia (%)')),
                ('weight_calificaciones', models.DecimalField(decimal_places=2, default=35.0, max_digits=5, verbose_name='Peso Calificaciones (%)')),
                ('attendance_red_max', models.DecimalField(decimal_places=2, default=70.0, max_digits=5, verbose_name='Asistencia máxima para Rojo (%)')),
                ('attendance_yellow_max', models.DecimalField(decimal_places=2, default=85.0, max_digits=5, verbose_name='Asistencia máxima para Amarillo (%)')),
                ('average_red_max', models.DecimalField(decimal_places=2, default=6.0, max_digits=4, verbose_name='Promedio máximo para Rojo')),
                ('average_yellow_max', models.DecimalField(decimal_places=2, default=7.0, max_digits=4, verbose_name='Promedio máximo para Amarillo')),
                ('severe_red_min', models.IntegerField(default=3, verbose_name='Faltas graves para Rojo (>)')),
                ('mild_yellow_min', models.IntegerField(default=5, verbose_name='Faltas leves para Amarillo (>)')),
            ],
            options={
                'verbose_name': 'Configuración de Cálculo de Riesgo',
                'verbose_name_plural': 'Configuración de Cálculo de Riesgo',
            },
        ),
    ]
