# Generated by Django 4.2.30 on 2026-06-26 19:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('academic_period', '0001_initial'),
        ('behavior_incident_type', '0001_initial'),
        ('behavior_severity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pendiente de sincronizar'), ('PROCESSING', 'En procesamiento'), ('SYNCED', 'Sincronizado'), ('ERROR', 'Error de sincronización'), ('CONFLICT', 'Conflicto detectado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de Sincronización')),
                ('sync_version', models.PositiveIntegerField(default=1, verbose_name='Versión de Sincronización')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado en')),
                ('device_origin', models.CharField(blank=True, max_length=40, null=True, verbose_name='Dispositivo de Origen')),
                ('conflict_resolved', models.BooleanField(default=False, verbose_name='Conflicto Resuelto')),
                ('conflict_notes', models.TextField(blank=True, default='', verbose_name='Notas de Conflicto')),
                ('incident_date', models.DateField(verbose_name='Fecha del Incidente')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripcion')),
                ('actions_taken', models.TextField(blank=True, default='', verbose_name='Acciones tomadas')),
                ('family_notified', models.BooleanField(default=False, verbose_name='Familia Notificada')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_incidents', to='academic_period.academicperiod', verbose_name='Periodo Academico')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_incidents', to='students.enrollment', verbose_name='Matricula')),
                ('incident_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='behavior_incident_type.incidenttype', verbose_name='Tipo de incidente')),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='behavior_severity.severity', verbose_name='Severidad')),
            ],
            options={
                'verbose_name': 'Incidente de Conducta',
                'verbose_name_plural': 'Incidentes de Conducta',
                'ordering': ['-incident_date'],
                'indexes': [models.Index(fields=['enrollment', 'academic_period'], name='behavior_co_enrollm_49bbcc_idx'), models.Index(fields=['academic_period', 'severity'], name='behavior_co_academi_30f227_idx'), models.Index(fields=['incident_date'], name='behavior_co_inciden_d46ca3_idx')],
            },
        ),
    ]
