# Generated by Django 4.2.30 on 2026-06-26 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grading_evaluation', '0001_initial'),
        ('academic_period', '0001_initial'),
        ('academic_subject_offering', '0001_initial'),
        ('grading_qualitative_scale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pendiente de sincronizar'), ('PROCESSING', 'En procesamiento'), ('SYNCED', 'Sincronizado'), ('ERROR', 'Error de sincronización'), ('CONFLICT', 'Conflicto detectado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de Sincronización')),
                ('sync_version', models.PositiveIntegerField(default=1, verbose_name='Versión de Sincronización')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado en')),
                ('device_origin', models.CharField(blank=True, max_length=40, null=True, verbose_name='Dispositivo de Origen')),
                ('conflict_resolved', models.BooleanField(default=False, verbose_name='Conflicto Resuelto')),
                ('conflict_notes', models.TextField(blank=True, default='', verbose_name='Notas de Conflicto')),
                ('grading_mode', models.CharField(choices=[('NUMERIC', 'Cuantitativa'), ('QUALITATIVE', 'Cualitativa')], default='NUMERIC', max_length=20, verbose_name='Modo de Calificacion')),
                ('numeric_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Puntuacion Numerica')),
                ('manually_overridden', models.BooleanField(default=False, verbose_name='Anulada Manualmente')),
                ('teacher_observation', models.TextField(blank=True, default='', verbose_name='Observacion del Docente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_notes_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.enrollment', verbose_name='Matricula')),
                ('evaluative_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading_evaluation.evaluativeactivity', verbose_name='Actividad Evaluativa')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_notes_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('qualitative_scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='grading_qualitative_scale.qualitativescale', verbose_name='Escala Cualitativa')),
            ],
            options={
                'verbose_name': 'Nota de Actividad',
                'verbose_name_plural': 'Notas de Actividades',
            },
        ),
        migrations.CreateModel(
            name='PeriodGradeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('formative_avg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Promedio Formativo')),
                ('summative_avg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Promedio Sumativo')),
                ('final_avg_truncated', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Promedio Final Truncado')),
                ('is_failing', models.BooleanField(default=False, verbose_name='Está Reprobando')),
                ('promotion_status', models.CharField(blank=True, choices=[('approved', 'Aprobado'), ('failed', 'Reprobado')], max_length=20, null=True, verbose_name='Estado de Promocion')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Calculado en')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_summaries', to='academic_period.academicperiod', verbose_name='Periodo Academico')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_summaries_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_summaries_calculated', to=settings.AUTH_USER_MODEL, verbose_name='Calculado por')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_summaries', to='students.enrollment', verbose_name='Matricula')),
                ('qualitative_scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='grading_qualitative_scale.qualitativescale', verbose_name='Escala Cualitativa')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_summaries', to='academic_subject_offering.subjectoffering', verbose_name='Oferta de Asignatura')),
            ],
            options={
                'verbose_name': 'Resumen de Calificaciones del Periodo',
                'verbose_name_plural': 'Resúmenes de Calificaciones del Periodo',
            },
        ),
        migrations.CreateModel(
            name='GradeChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('previous_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota Anterior')),
                ('new_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota Nueva')),
                ('reason', models.TextField(verbose_name='Razon del Cambio')),
                ('reason_code', models.CharField(blank=True, max_length=30, verbose_name='Codigo de Razon')),
                ('origin', models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORT', 'Importacion'), ('SYNC', 'Sincronizacion')], default='MANUAL', max_length=20, verbose_name='Origen')),
                ('device_origin', models.CharField(blank=True, max_length=40, null=True, verbose_name='Dispositivo de Origen')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='Modificado en')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_changes_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('new_qualitative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_grade_changes', to='grading_qualitative_scale.qualitativescale', verbose_name='Nueva Escala Cualitativa')),
                ('previous_qualitative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_grade_changes', to='grading_qualitative_scale.qualitativescale', verbose_name='Escala Cualitativa Anterior')),
                ('student_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='grading_student_note.studentnote', verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Historial de Cambio de Calificacion',
                'verbose_name_plural': 'Historiales de Cambio de Calificacion',
                'ordering': ['-modified_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['enrollment', 'evaluative_activity'], name='grading_stu_enrollm_cb247c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['evaluative_activity', 'numeric_score'], name='grading_stu_evaluat_03de08_idx'),
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['sync_status'], name='grading_stu_sync_st_a0ae52_idx'),
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['enrollment', 'sync_status'], name='grading_stu_enrollm_53094f_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentnote',
            constraint=models.UniqueConstraint(condition=models.Q(('evaluative_activity__isnull', False)), fields=('enrollment', 'evaluative_activity'), name='unique_enrollment_activity'),
        ),
        migrations.AddIndex(
            model_name='periodgradesummary',
            index=models.Index(fields=['academic_period', 'subject_offering'], name='grading_stu_academi_0a3012_idx'),
        ),
        migrations.AddIndex(
            model_name='periodgradesummary',
            index=models.Index(fields=['enrollment', 'academic_period'], name='grading_stu_enrollm_7f2f01_idx'),
        ),
        migrations.AddIndex(
            model_name='periodgradesummary',
            index=models.Index(fields=['is_failing', 'academic_period'], name='grading_stu_is_fail_e590f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='periodgradesummary',
            constraint=models.UniqueConstraint(fields=('enrollment', 'subject_offering', 'academic_period'), name='unique_period_grade_summary'),
        ),
        migrations.AddIndex(
            model_name='gradechangehistory',
            index=models.Index(fields=['student_note', 'modified_at'], name='grading_stu_student_b8b6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='gradechangehistory',
            index=models.Index(fields=['modified_by_user', 'modified_at'], name='grading_stu_modifie_833757_idx'),
        ),
    ]
