# Generated by Django 4.2.30 on 2026-07-10 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('academic_subject_offering', '0001_initial'),
        ('institutions_school_year', '0001_initial'),
        ('grading_student_note', '0002_studentnote_db_level_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualGradeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('annual_final_avg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Promedio Final Anual')),
                ('is_failing', models.BooleanField(default=False, verbose_name='Reprobó la materia')),
                ('promotion_status', models.CharField(blank=True, choices=[('approved', 'Aprobado'), ('failed', 'Reprobado')], max_length=20, null=True, verbose_name='Estado de Promoción')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='Resultado Anual Definitivo')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Calculado en')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_grade_summaries_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_grade_summaries_calculated', to=settings.AUTH_USER_MODEL, verbose_name='Calculado por')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_grade_summaries', to='students.enrollment', verbose_name='Matrícula')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_grade_summaries', to='institutions_school_year.schoolyear', verbose_name='Año Escolar')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_grade_summaries', to='academic_subject_offering.subjectoffering', verbose_name='Oferta de Asignatura')),
            ],
            options={
                'verbose_name': 'Resumen Anual de Calificaciones',
                'verbose_name_plural': 'Resúmenes Anuales de Calificaciones',
                'indexes': [models.Index(fields=['school_year', 'subject_offering'], name='grading_stu_school__39656b_idx'), models.Index(fields=['enrollment', 'school_year'], name='grading_stu_enrollm_65e512_idx'), models.Index(fields=['is_failing', 'school_year'], name='grading_stu_is_fail_d396ed_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='annualgradesummary',
            constraint=models.UniqueConstraint(fields=('enrollment', 'subject_offering', 'school_year'), name='unique_annual_grade_summary'),
        ),
    ]
