# Generated by Django 4.2.30 on 2026-07-15 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_enrollment_sync_status'),
        ('grading_student_note', '0003_annualgradesummary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualgradesummary',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_grade_summaries', to='students.enrollment', verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='periodgradesummary',
            name='is_failing',
            field=models.BooleanField(default=False, verbose_name='Esta Reprobando'),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='sync_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de sincronizar'), ('PROCESSING', 'En procesamiento'), ('SYNCED', 'Sincronizado'), ('ERROR', 'Error de sincronización'), ('CONFLICT', 'Conflicto detectado'), ('ROLLED_BACK', 'Revertido')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de Sincronización'),
        ),
    ]
