# Generated by Django 4.2.30 on 2026-06-26 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions_academic_grade', '0001_initial'),
        ('academic_subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAcademicConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('weekly_hours', models.IntegerField(verbose_name='Horas Semanales')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obligatoria')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('academic_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_academic_configs', to='institutions_academic_grade.academicgrade', verbose_name='Grado Académico')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_configs', to='academic_subject.subject', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Configuración de Materia por Grado',
                'verbose_name_plural': 'Configuraciones de Materia por Grado',
                'ordering': ['subject'],
            },
        ),
        migrations.AddConstraint(
            model_name='subjectacademicconfig',
            constraint=models.UniqueConstraint(fields=('subject', 'academic_grade'), name='unique_subject_academic_grade'),
        ),
    ]
