# Generated by Django 4.2.30 on 2026-06-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_absence_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absencetype',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de Ausencia', 'verbose_name_plural': 'Tipos de Ausencia'},
        ),
        migrations.AlterField(
            model_name='absencetype',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='absencetype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='absencetype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='absencetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
